// Code generated by protoc-gen-go. DO NOT EDIT.
// source: collateralize.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 放贷信息
type Collateralize struct {
	CollateralizeId        string          `protobuf:"bytes,1,opt,name=collateralizeId,proto3" json:"collateralizeId,omitempty"`
	TotalBalance           int64           `protobuf:"varint,2,opt,name=totalBalance,proto3" json:"totalBalance,omitempty"`
	DebtCeiling            int64           `protobuf:"varint,3,opt,name=debtCeiling,proto3" json:"debtCeiling,omitempty"`
	LiquidationRatio       int64           `protobuf:"varint,4,opt,name=liquidationRatio,proto3" json:"liquidationRatio,omitempty"`
	StabilityFeeRatio      int64           `protobuf:"varint,5,opt,name=stabilityFeeRatio,proto3" json:"stabilityFeeRatio,omitempty"`
	CreateAddr             string          `protobuf:"bytes,6,opt,name=createAddr,proto3" json:"createAddr,omitempty"`
	Balance                int64           `protobuf:"varint,7,opt,name=balance,proto3" json:"balance,omitempty"`
	BorrowRecords          []*BorrowRecord `protobuf:"bytes,8,rep,name=borrowRecords,proto3" json:"borrowRecords,omitempty"`
	InvalidRecords         []*BorrowRecord `protobuf:"bytes,9,rep,name=InvalidRecords,proto3" json:"InvalidRecords,omitempty"`
	Status                 int32           `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	LatestLiquidationPrice int64           `protobuf:"varint,11,opt,name=latestLiquidationPrice,proto3" json:"latestLiquidationPrice,omitempty"`
	Period                 int64           `protobuf:"varint,12,opt,name=period,proto3" json:"period,omitempty"`
	LatestExpireTime       int64           `protobuf:"varint,13,opt,name=latestExpireTime,proto3" json:"latestExpireTime,omitempty"`
	CollBalance            int64           `protobuf:"varint,14,opt,name=collBalance,proto3" json:"collBalance,omitempty"`
	PreStatus              int32           `protobuf:"varint,15,opt,name=preStatus,proto3" json:"preStatus,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}        `json:"-"`
	XXX_unrecognized       []byte          `json:"-"`
	XXX_sizecache          int32           `json:"-"`
}

func (m *Collateralize) Reset()         { *m = Collateralize{} }
func (m *Collateralize) String() string { return proto.CompactTextString(m) }
func (*Collateralize) ProtoMessage()    {}
func (*Collateralize) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{0}
}

func (m *Collateralize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Collateralize.Unmarshal(m, b)
}
func (m *Collateralize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Collateralize.Marshal(b, m, deterministic)
}
func (m *Collateralize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Collateralize.Merge(m, src)
}
func (m *Collateralize) XXX_Size() int {
	return xxx_messageInfo_Collateralize.Size(m)
}
func (m *Collateralize) XXX_DiscardUnknown() {
	xxx_messageInfo_Collateralize.DiscardUnknown(m)
}

var xxx_messageInfo_Collateralize proto.InternalMessageInfo

func (m *Collateralize) GetCollateralizeId() string {
	if m != nil {
		return m.CollateralizeId
	}
	return ""
}

func (m *Collateralize) GetTotalBalance() int64 {
	if m != nil {
		return m.TotalBalance
	}
	return 0
}

func (m *Collateralize) GetDebtCeiling() int64 {
	if m != nil {
		return m.DebtCeiling
	}
	return 0
}

func (m *Collateralize) GetLiquidationRatio() int64 {
	if m != nil {
		return m.LiquidationRatio
	}
	return 0
}

func (m *Collateralize) GetStabilityFeeRatio() int64 {
	if m != nil {
		return m.StabilityFeeRatio
	}
	return 0
}

func (m *Collateralize) GetCreateAddr() string {
	if m != nil {
		return m.CreateAddr
	}
	return ""
}

func (m *Collateralize) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Collateralize) GetBorrowRecords() []*BorrowRecord {
	if m != nil {
		return m.BorrowRecords
	}
	return nil
}

func (m *Collateralize) GetInvalidRecords() []*BorrowRecord {
	if m != nil {
		return m.InvalidRecords
	}
	return nil
}

func (m *Collateralize) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Collateralize) GetLatestLiquidationPrice() int64 {
	if m != nil {
		return m.LatestLiquidationPrice
	}
	return 0
}

func (m *Collateralize) GetPeriod() int64 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *Collateralize) GetLatestExpireTime() int64 {
	if m != nil {
		return m.LatestExpireTime
	}
	return 0
}

func (m *Collateralize) GetCollBalance() int64 {
	if m != nil {
		return m.CollBalance
	}
	return 0
}

func (m *Collateralize) GetPreStatus() int32 {
	if m != nil {
		return m.PreStatus
	}
	return 0
}

// 借出记录
type BorrowRecord struct {
	AccountAddr          string   `protobuf:"bytes,1,opt,name=accountAddr,proto3" json:"accountAddr,omitempty"`
	StartTime            int64    `protobuf:"varint,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
	CollateralValue      int64    `protobuf:"varint,3,opt,name=collateralValue,proto3" json:"collateralValue,omitempty"`
	CollateralPrice      int64    `protobuf:"varint,4,opt,name=collateralPrice,proto3" json:"collateralPrice,omitempty"`
	DebtValue            int64    `protobuf:"varint,5,opt,name=debtValue,proto3" json:"debtValue,omitempty"`
	LiquidationPrice     int64    `protobuf:"varint,6,opt,name=liquidationPrice,proto3" json:"liquidationPrice,omitempty"`
	Status               int32    `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	LiquidateTime        int64    `protobuf:"varint,8,opt,name=liquidateTime,proto3" json:"liquidateTime,omitempty"`
	ExpireTime           int64    `protobuf:"varint,9,opt,name=expireTime,proto3" json:"expireTime,omitempty"`
	PreStatus            int32    `protobuf:"varint,10,opt,name=preStatus,proto3" json:"preStatus,omitempty"`
	RecordId             string   `protobuf:"bytes,11,opt,name=recordId,proto3" json:"recordId,omitempty"`
	CollateralizeId      string   `protobuf:"bytes,12,opt,name=collateralizeId,proto3" json:"collateralizeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BorrowRecord) Reset()         { *m = BorrowRecord{} }
func (m *BorrowRecord) String() string { return proto.CompactTextString(m) }
func (*BorrowRecord) ProtoMessage()    {}
func (*BorrowRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{1}
}

func (m *BorrowRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BorrowRecord.Unmarshal(m, b)
}
func (m *BorrowRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BorrowRecord.Marshal(b, m, deterministic)
}
func (m *BorrowRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BorrowRecord.Merge(m, src)
}
func (m *BorrowRecord) XXX_Size() int {
	return xxx_messageInfo_BorrowRecord.Size(m)
}
func (m *BorrowRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_BorrowRecord.DiscardUnknown(m)
}

var xxx_messageInfo_BorrowRecord proto.InternalMessageInfo

func (m *BorrowRecord) GetAccountAddr() string {
	if m != nil {
		return m.AccountAddr
	}
	return ""
}

func (m *BorrowRecord) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *BorrowRecord) GetCollateralValue() int64 {
	if m != nil {
		return m.CollateralValue
	}
	return 0
}

func (m *BorrowRecord) GetCollateralPrice() int64 {
	if m != nil {
		return m.CollateralPrice
	}
	return 0
}

func (m *BorrowRecord) GetDebtValue() int64 {
	if m != nil {
		return m.DebtValue
	}
	return 0
}

func (m *BorrowRecord) GetLiquidationPrice() int64 {
	if m != nil {
		return m.LiquidationPrice
	}
	return 0
}

func (m *BorrowRecord) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *BorrowRecord) GetLiquidateTime() int64 {
	if m != nil {
		return m.LiquidateTime
	}
	return 0
}

func (m *BorrowRecord) GetExpireTime() int64 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

func (m *BorrowRecord) GetPreStatus() int32 {
	if m != nil {
		return m.PreStatus
	}
	return 0
}

func (m *BorrowRecord) GetRecordId() string {
	if m != nil {
		return m.RecordId
	}
	return ""
}

func (m *BorrowRecord) GetCollateralizeId() string {
	if m != nil {
		return m.CollateralizeId
	}
	return ""
}

// 借出记录展示
type QueryBorrowRecord struct {
	AccountAddr          string   `protobuf:"bytes,1,opt,name=accountAddr,proto3" json:"accountAddr,omitempty"`
	StartTime            int64    `protobuf:"varint,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
	CollateralValue      int64    `protobuf:"varint,3,opt,name=collateralValue,proto3" json:"collateralValue,omitempty"`
	CollateralToken      string   `protobuf:"bytes,4,opt,name=collateralToken,proto3" json:"collateralToken,omitempty"`
	CollateralPrice      int64    `protobuf:"varint,5,opt,name=collateralPrice,proto3" json:"collateralPrice,omitempty"`
	DebtValue            int64    `protobuf:"varint,6,opt,name=debtValue,proto3" json:"debtValue,omitempty"`
	LiquidationPrice     int64    `protobuf:"varint,7,opt,name=liquidationPrice,proto3" json:"liquidationPrice,omitempty"`
	Status               int32    `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	LiquidateTime        int64    `protobuf:"varint,9,opt,name=liquidateTime,proto3" json:"liquidateTime,omitempty"`
	ExpireTime           int64    `protobuf:"varint,10,opt,name=expireTime,proto3" json:"expireTime,omitempty"`
	PreStatus            int32    `protobuf:"varint,11,opt,name=preStatus,proto3" json:"preStatus,omitempty"`
	RecordId             string   `protobuf:"bytes,12,opt,name=recordId,proto3" json:"recordId,omitempty"`
	CollateralizeId      string   `protobuf:"bytes,13,opt,name=collateralizeId,proto3" json:"collateralizeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryBorrowRecord) Reset()         { *m = QueryBorrowRecord{} }
func (m *QueryBorrowRecord) String() string { return proto.CompactTextString(m) }
func (*QueryBorrowRecord) ProtoMessage()    {}
func (*QueryBorrowRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{2}
}

func (m *QueryBorrowRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryBorrowRecord.Unmarshal(m, b)
}
func (m *QueryBorrowRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryBorrowRecord.Marshal(b, m, deterministic)
}
func (m *QueryBorrowRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBorrowRecord.Merge(m, src)
}
func (m *QueryBorrowRecord) XXX_Size() int {
	return xxx_messageInfo_QueryBorrowRecord.Size(m)
}
func (m *QueryBorrowRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBorrowRecord.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBorrowRecord proto.InternalMessageInfo

func (m *QueryBorrowRecord) GetAccountAddr() string {
	if m != nil {
		return m.AccountAddr
	}
	return ""
}

func (m *QueryBorrowRecord) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *QueryBorrowRecord) GetCollateralValue() int64 {
	if m != nil {
		return m.CollateralValue
	}
	return 0
}

func (m *QueryBorrowRecord) GetCollateralToken() string {
	if m != nil {
		return m.CollateralToken
	}
	return ""
}

func (m *QueryBorrowRecord) GetCollateralPrice() int64 {
	if m != nil {
		return m.CollateralPrice
	}
	return 0
}

func (m *QueryBorrowRecord) GetDebtValue() int64 {
	if m != nil {
		return m.DebtValue
	}
	return 0
}

func (m *QueryBorrowRecord) GetLiquidationPrice() int64 {
	if m != nil {
		return m.LiquidationPrice
	}
	return 0
}

func (m *QueryBorrowRecord) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *QueryBorrowRecord) GetLiquidateTime() int64 {
	if m != nil {
		return m.LiquidateTime
	}
	return 0
}

func (m *QueryBorrowRecord) GetExpireTime() int64 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

func (m *QueryBorrowRecord) GetPreStatus() int32 {
	if m != nil {
		return m.PreStatus
	}
	return 0
}

func (m *QueryBorrowRecord) GetRecordId() string {
	if m != nil {
		return m.RecordId
	}
	return ""
}

func (m *QueryBorrowRecord) GetCollateralizeId() string {
	if m != nil {
		return m.CollateralizeId
	}
	return ""
}

// 资产价格记录
type AssetPriceRecord struct {
	RecordTime           int64    `protobuf:"varint,1,opt,name=recordTime,proto3" json:"recordTime,omitempty"`
	BtyPrice             int64    `protobuf:"varint,2,opt,name=btyPrice,proto3" json:"btyPrice,omitempty"`
	BtcPrice             int64    `protobuf:"varint,3,opt,name=btcPrice,proto3" json:"btcPrice,omitempty"`
	EthPrice             int64    `protobuf:"varint,4,opt,name=ethPrice,proto3" json:"ethPrice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssetPriceRecord) Reset()         { *m = AssetPriceRecord{} }
func (m *AssetPriceRecord) String() string { return proto.CompactTextString(m) }
func (*AssetPriceRecord) ProtoMessage()    {}
func (*AssetPriceRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{3}
}

func (m *AssetPriceRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetPriceRecord.Unmarshal(m, b)
}
func (m *AssetPriceRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetPriceRecord.Marshal(b, m, deterministic)
}
func (m *AssetPriceRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetPriceRecord.Merge(m, src)
}
func (m *AssetPriceRecord) XXX_Size() int {
	return xxx_messageInfo_AssetPriceRecord.Size(m)
}
func (m *AssetPriceRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetPriceRecord.DiscardUnknown(m)
}

var xxx_messageInfo_AssetPriceRecord proto.InternalMessageInfo

func (m *AssetPriceRecord) GetRecordTime() int64 {
	if m != nil {
		return m.RecordTime
	}
	return 0
}

func (m *AssetPriceRecord) GetBtyPrice() int64 {
	if m != nil {
		return m.BtyPrice
	}
	return 0
}

func (m *AssetPriceRecord) GetBtcPrice() int64 {
	if m != nil {
		return m.BtcPrice
	}
	return 0
}

func (m *AssetPriceRecord) GetEthPrice() int64 {
	if m != nil {
		return m.EthPrice
	}
	return 0
}

// action
type CollateralizeAction struct {
	// Types that are valid to be assigned to Value:
	//	*CollateralizeAction_Create
	//	*CollateralizeAction_Borrow
	//	*CollateralizeAction_Repay
	//	*CollateralizeAction_Append
	//	*CollateralizeAction_Feed
	//	*CollateralizeAction_Retrieve
	//	*CollateralizeAction_Manage
	//	*CollateralizeAction_Coller
	//	*CollateralizeAction_Lend
	Value                isCollateralizeAction_Value `protobuf_oneof:"value"`
	Ty                   int32                       `protobuf:"varint,10,opt,name=ty,proto3" json:"ty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *CollateralizeAction) Reset()         { *m = CollateralizeAction{} }
func (m *CollateralizeAction) String() string { return proto.CompactTextString(m) }
func (*CollateralizeAction) ProtoMessage()    {}
func (*CollateralizeAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{4}
}

func (m *CollateralizeAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollateralizeAction.Unmarshal(m, b)
}
func (m *CollateralizeAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollateralizeAction.Marshal(b, m, deterministic)
}
func (m *CollateralizeAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollateralizeAction.Merge(m, src)
}
func (m *CollateralizeAction) XXX_Size() int {
	return xxx_messageInfo_CollateralizeAction.Size(m)
}
func (m *CollateralizeAction) XXX_DiscardUnknown() {
	xxx_messageInfo_CollateralizeAction.DiscardUnknown(m)
}

var xxx_messageInfo_CollateralizeAction proto.InternalMessageInfo

type isCollateralizeAction_Value interface {
	isCollateralizeAction_Value()
}

type CollateralizeAction_Create struct {
	Create *CollateralizeCreate `protobuf:"bytes,1,opt,name=create,proto3,oneof"`
}

type CollateralizeAction_Borrow struct {
	Borrow *CollateralizeBorrow `protobuf:"bytes,2,opt,name=borrow,proto3,oneof"`
}

type CollateralizeAction_Repay struct {
	Repay *CollateralizeRepay `protobuf:"bytes,3,opt,name=repay,proto3,oneof"`
}

type CollateralizeAction_Append struct {
	Append *CollateralizeAppend `protobuf:"bytes,4,opt,name=append,proto3,oneof"`
}

type CollateralizeAction_Feed struct {
	Feed *CollateralizeFeed `protobuf:"bytes,5,opt,name=feed,proto3,oneof"`
}

type CollateralizeAction_Retrieve struct {
	Retrieve *CollateralizeRetrieve `protobuf:"bytes,6,opt,name=retrieve,proto3,oneof"`
}

type CollateralizeAction_Manage struct {
	Manage *CollateralizeManage `protobuf:"bytes,7,opt,name=manage,proto3,oneof"`
}

type CollateralizeAction_Coller struct {
	Coller *CollateralizeColler `protobuf:"bytes,8,opt,name=coller,proto3,oneof"`
}

type CollateralizeAction_Lend struct {
	Lend *CollateralizeLend `protobuf:"bytes,9,opt,name=lend,proto3,oneof"`
}

func (*CollateralizeAction_Create) isCollateralizeAction_Value() {}

func (*CollateralizeAction_Borrow) isCollateralizeAction_Value() {}

func (*CollateralizeAction_Repay) isCollateralizeAction_Value() {}

func (*CollateralizeAction_Append) isCollateralizeAction_Value() {}

func (*CollateralizeAction_Feed) isCollateralizeAction_Value() {}

func (*CollateralizeAction_Retrieve) isCollateralizeAction_Value() {}

func (*CollateralizeAction_Manage) isCollateralizeAction_Value() {}

func (*CollateralizeAction_Coller) isCollateralizeAction_Value() {}

func (*CollateralizeAction_Lend) isCollateralizeAction_Value() {}

func (m *CollateralizeAction) GetValue() isCollateralizeAction_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *CollateralizeAction) GetCreate() *CollateralizeCreate {
	if x, ok := m.GetValue().(*CollateralizeAction_Create); ok {
		return x.Create
	}
	return nil
}

func (m *CollateralizeAction) GetBorrow() *CollateralizeBorrow {
	if x, ok := m.GetValue().(*CollateralizeAction_Borrow); ok {
		return x.Borrow
	}
	return nil
}

func (m *CollateralizeAction) GetRepay() *CollateralizeRepay {
	if x, ok := m.GetValue().(*CollateralizeAction_Repay); ok {
		return x.Repay
	}
	return nil
}

func (m *CollateralizeAction) GetAppend() *CollateralizeAppend {
	if x, ok := m.GetValue().(*CollateralizeAction_Append); ok {
		return x.Append
	}
	return nil
}

func (m *CollateralizeAction) GetFeed() *CollateralizeFeed {
	if x, ok := m.GetValue().(*CollateralizeAction_Feed); ok {
		return x.Feed
	}
	return nil
}

func (m *CollateralizeAction) GetRetrieve() *CollateralizeRetrieve {
	if x, ok := m.GetValue().(*CollateralizeAction_Retrieve); ok {
		return x.Retrieve
	}
	return nil
}

func (m *CollateralizeAction) GetManage() *CollateralizeManage {
	if x, ok := m.GetValue().(*CollateralizeAction_Manage); ok {
		return x.Manage
	}
	return nil
}

func (m *CollateralizeAction) GetColler() *CollateralizeColler {
	if x, ok := m.GetValue().(*CollateralizeAction_Coller); ok {
		return x.Coller
	}
	return nil
}

func (m *CollateralizeAction) GetLend() *CollateralizeLend {
	if x, ok := m.GetValue().(*CollateralizeAction_Lend); ok {
		return x.Lend
	}
	return nil
}

func (m *CollateralizeAction) GetTy() int32 {
	if m != nil {
		return m.Ty
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CollateralizeAction) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CollateralizeAction_Create)(nil),
		(*CollateralizeAction_Borrow)(nil),
		(*CollateralizeAction_Repay)(nil),
		(*CollateralizeAction_Append)(nil),
		(*CollateralizeAction_Feed)(nil),
		(*CollateralizeAction_Retrieve)(nil),
		(*CollateralizeAction_Manage)(nil),
		(*CollateralizeAction_Coller)(nil),
		(*CollateralizeAction_Lend)(nil),
	}
}

type CollateralizeManage struct {
	DebtCeiling          int64    `protobuf:"varint,1,opt,name=debtCeiling,proto3" json:"debtCeiling,omitempty"`
	LiquidationRatio     int64    `protobuf:"varint,2,opt,name=liquidationRatio,proto3" json:"liquidationRatio,omitempty"`
	StabilityFeeRatio    int64    `protobuf:"varint,3,opt,name=stabilityFeeRatio,proto3" json:"stabilityFeeRatio,omitempty"`
	Period               int64    `protobuf:"varint,4,opt,name=period,proto3" json:"period,omitempty"`
	TotalBalance         int64    `protobuf:"varint,5,opt,name=totalBalance,proto3" json:"totalBalance,omitempty"`
	CurrentTime          int64    `protobuf:"varint,6,opt,name=currentTime,proto3" json:"currentTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollateralizeManage) Reset()         { *m = CollateralizeManage{} }
func (m *CollateralizeManage) String() string { return proto.CompactTextString(m) }
func (*CollateralizeManage) ProtoMessage()    {}
func (*CollateralizeManage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{5}
}

func (m *CollateralizeManage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollateralizeManage.Unmarshal(m, b)
}
func (m *CollateralizeManage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollateralizeManage.Marshal(b, m, deterministic)
}
func (m *CollateralizeManage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollateralizeManage.Merge(m, src)
}
func (m *CollateralizeManage) XXX_Size() int {
	return xxx_messageInfo_CollateralizeManage.Size(m)
}
func (m *CollateralizeManage) XXX_DiscardUnknown() {
	xxx_messageInfo_CollateralizeManage.DiscardUnknown(m)
}

var xxx_messageInfo_CollateralizeManage proto.InternalMessageInfo

func (m *CollateralizeManage) GetDebtCeiling() int64 {
	if m != nil {
		return m.DebtCeiling
	}
	return 0
}

func (m *CollateralizeManage) GetLiquidationRatio() int64 {
	if m != nil {
		return m.LiquidationRatio
	}
	return 0
}

func (m *CollateralizeManage) GetStabilityFeeRatio() int64 {
	if m != nil {
		return m.StabilityFeeRatio
	}
	return 0
}

func (m *CollateralizeManage) GetPeriod() int64 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *CollateralizeManage) GetTotalBalance() int64 {
	if m != nil {
		return m.TotalBalance
	}
	return 0
}

func (m *CollateralizeManage) GetCurrentTime() int64 {
	if m != nil {
		return m.CurrentTime
	}
	return 0
}

type CollateralizeAddr struct {
	SuperAddrs           []string `protobuf:"bytes,1,rep,name=superAddrs,proto3" json:"superAddrs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollateralizeAddr) Reset()         { *m = CollateralizeAddr{} }
func (m *CollateralizeAddr) String() string { return proto.CompactTextString(m) }
func (*CollateralizeAddr) ProtoMessage()    {}
func (*CollateralizeAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{6}
}

func (m *CollateralizeAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollateralizeAddr.Unmarshal(m, b)
}
func (m *CollateralizeAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollateralizeAddr.Marshal(b, m, deterministic)
}
func (m *CollateralizeAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollateralizeAddr.Merge(m, src)
}
func (m *CollateralizeAddr) XXX_Size() int {
	return xxx_messageInfo_CollateralizeAddr.Size(m)
}
func (m *CollateralizeAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_CollateralizeAddr.DiscardUnknown(m)
}

var xxx_messageInfo_CollateralizeAddr proto.InternalMessageInfo

func (m *CollateralizeAddr) GetSuperAddrs() []string {
	if m != nil {
		return m.SuperAddrs
	}
	return nil
}

// 带配置创建放贷
type CollateralizeLend struct {
	TotalBalance         int64    `protobuf:"varint,1,opt,name=totalBalance,proto3" json:"totalBalance,omitempty"`
	LiquidationRatio     int64    `protobuf:"varint,2,opt,name=liquidationRatio,proto3" json:"liquidationRatio,omitempty"`
	StabilityFeeRatio    int64    `protobuf:"varint,3,opt,name=stabilityFeeRatio,proto3" json:"stabilityFeeRatio,omitempty"`
	Period               int64    `protobuf:"varint,4,opt,name=period,proto3" json:"period,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollateralizeLend) Reset()         { *m = CollateralizeLend{} }
func (m *CollateralizeLend) String() string { return proto.CompactTextString(m) }
func (*CollateralizeLend) ProtoMessage()    {}
func (*CollateralizeLend) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{7}
}

func (m *CollateralizeLend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollateralizeLend.Unmarshal(m, b)
}
func (m *CollateralizeLend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollateralizeLend.Marshal(b, m, deterministic)
}
func (m *CollateralizeLend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollateralizeLend.Merge(m, src)
}
func (m *CollateralizeLend) XXX_Size() int {
	return xxx_messageInfo_CollateralizeLend.Size(m)
}
func (m *CollateralizeLend) XXX_DiscardUnknown() {
	xxx_messageInfo_CollateralizeLend.DiscardUnknown(m)
}

var xxx_messageInfo_CollateralizeLend proto.InternalMessageInfo

func (m *CollateralizeLend) GetTotalBalance() int64 {
	if m != nil {
		return m.TotalBalance
	}
	return 0
}

func (m *CollateralizeLend) GetLiquidationRatio() int64 {
	if m != nil {
		return m.LiquidationRatio
	}
	return 0
}

func (m *CollateralizeLend) GetStabilityFeeRatio() int64 {
	if m != nil {
		return m.StabilityFeeRatio
	}
	return 0
}

func (m *CollateralizeLend) GetPeriod() int64 {
	if m != nil {
		return m.Period
	}
	return 0
}

// 放贷配置记录
type CollateralizeColler struct {
	CollerAddr           string                  `protobuf:"bytes,1,opt,name=collerAddr,proto3" json:"collerAddr,omitempty"`
	Balance              int64                   `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Item                 *CollateralizeTokenItem `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`
	Op                   string                  `protobuf:"bytes,4,opt,name=op,proto3" json:"op,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *CollateralizeColler) Reset()         { *m = CollateralizeColler{} }
func (m *CollateralizeColler) String() string { return proto.CompactTextString(m) }
func (*CollateralizeColler) ProtoMessage()    {}
func (*CollateralizeColler) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{8}
}

func (m *CollateralizeColler) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollateralizeColler.Unmarshal(m, b)
}
func (m *CollateralizeColler) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollateralizeColler.Marshal(b, m, deterministic)
}
func (m *CollateralizeColler) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollateralizeColler.Merge(m, src)
}
func (m *CollateralizeColler) XXX_Size() int {
	return xxx_messageInfo_CollateralizeColler.Size(m)
}
func (m *CollateralizeColler) XXX_DiscardUnknown() {
	xxx_messageInfo_CollateralizeColler.DiscardUnknown(m)
}

var xxx_messageInfo_CollateralizeColler proto.InternalMessageInfo

func (m *CollateralizeColler) GetCollerAddr() string {
	if m != nil {
		return m.CollerAddr
	}
	return ""
}

func (m *CollateralizeColler) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *CollateralizeColler) GetItem() *CollateralizeTokenItem {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *CollateralizeColler) GetOp() string {
	if m != nil {
		return m.Op
	}
	return ""
}

type CollateralizeTokenItem struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollateralizeTokenItem) Reset()         { *m = CollateralizeTokenItem{} }
func (m *CollateralizeTokenItem) String() string { return proto.CompactTextString(m) }
func (*CollateralizeTokenItem) ProtoMessage()    {}
func (*CollateralizeTokenItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{9}
}

func (m *CollateralizeTokenItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollateralizeTokenItem.Unmarshal(m, b)
}
func (m *CollateralizeTokenItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollateralizeTokenItem.Marshal(b, m, deterministic)
}
func (m *CollateralizeTokenItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollateralizeTokenItem.Merge(m, src)
}
func (m *CollateralizeTokenItem) XXX_Size() int {
	return xxx_messageInfo_CollateralizeTokenItem.Size(m)
}
func (m *CollateralizeTokenItem) XXX_DiscardUnknown() {
	xxx_messageInfo_CollateralizeTokenItem.DiscardUnknown(m)
}

var xxx_messageInfo_CollateralizeTokenItem proto.InternalMessageInfo

func (m *CollateralizeTokenItem) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CollateralizeTokenItem) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CollateralizeTokenConfig struct {
	Items                []*CollateralizeTokenItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *CollateralizeTokenConfig) Reset()         { *m = CollateralizeTokenConfig{} }
func (m *CollateralizeTokenConfig) String() string { return proto.CompactTextString(m) }
func (*CollateralizeTokenConfig) ProtoMessage()    {}
func (*CollateralizeTokenConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{10}
}

func (m *CollateralizeTokenConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollateralizeTokenConfig.Unmarshal(m, b)
}
func (m *CollateralizeTokenConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollateralizeTokenConfig.Marshal(b, m, deterministic)
}
func (m *CollateralizeTokenConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollateralizeTokenConfig.Merge(m, src)
}
func (m *CollateralizeTokenConfig) XXX_Size() int {
	return xxx_messageInfo_CollateralizeTokenConfig.Size(m)
}
func (m *CollateralizeTokenConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_CollateralizeTokenConfig.DiscardUnknown(m)
}

var xxx_messageInfo_CollateralizeTokenConfig proto.InternalMessageInfo

func (m *CollateralizeTokenConfig) GetItems() []*CollateralizeTokenItem {
	if m != nil {
		return m.Items
	}
	return nil
}

// 创建放贷
type CollateralizeCreate struct {
	TotalBalance         int64    `protobuf:"varint,1,opt,name=totalBalance,proto3" json:"totalBalance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollateralizeCreate) Reset()         { *m = CollateralizeCreate{} }
func (m *CollateralizeCreate) String() string { return proto.CompactTextString(m) }
func (*CollateralizeCreate) ProtoMessage()    {}
func (*CollateralizeCreate) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{11}
}

func (m *CollateralizeCreate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollateralizeCreate.Unmarshal(m, b)
}
func (m *CollateralizeCreate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollateralizeCreate.Marshal(b, m, deterministic)
}
func (m *CollateralizeCreate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollateralizeCreate.Merge(m, src)
}
func (m *CollateralizeCreate) XXX_Size() int {
	return xxx_messageInfo_CollateralizeCreate.Size(m)
}
func (m *CollateralizeCreate) XXX_DiscardUnknown() {
	xxx_messageInfo_CollateralizeCreate.DiscardUnknown(m)
}

var xxx_messageInfo_CollateralizeCreate proto.InternalMessageInfo

func (m *CollateralizeCreate) GetTotalBalance() int64 {
	if m != nil {
		return m.TotalBalance
	}
	return 0
}

// 质押借出
type CollateralizeBorrow struct {
	CollateralizeId      string   `protobuf:"bytes,1,opt,name=collateralizeId,proto3" json:"collateralizeId,omitempty"`
	Value                int64    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollateralizeBorrow) Reset()         { *m = CollateralizeBorrow{} }
func (m *CollateralizeBorrow) String() string { return proto.CompactTextString(m) }
func (*CollateralizeBorrow) ProtoMessage()    {}
func (*CollateralizeBorrow) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{12}
}

func (m *CollateralizeBorrow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollateralizeBorrow.Unmarshal(m, b)
}
func (m *CollateralizeBorrow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollateralizeBorrow.Marshal(b, m, deterministic)
}
func (m *CollateralizeBorrow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollateralizeBorrow.Merge(m, src)
}
func (m *CollateralizeBorrow) XXX_Size() int {
	return xxx_messageInfo_CollateralizeBorrow.Size(m)
}
func (m *CollateralizeBorrow) XXX_DiscardUnknown() {
	xxx_messageInfo_CollateralizeBorrow.DiscardUnknown(m)
}

var xxx_messageInfo_CollateralizeBorrow proto.InternalMessageInfo

func (m *CollateralizeBorrow) GetCollateralizeId() string {
	if m != nil {
		return m.CollateralizeId
	}
	return ""
}

func (m *CollateralizeBorrow) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

// 质押清算
type CollateralizeRepay struct {
	CollateralizeId      string   `protobuf:"bytes,1,opt,name=collateralizeId,proto3" json:"collateralizeId,omitempty"`
	RecordId             string   `protobuf:"bytes,2,opt,name=recordId,proto3" json:"recordId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollateralizeRepay) Reset()         { *m = CollateralizeRepay{} }
func (m *CollateralizeRepay) String() string { return proto.CompactTextString(m) }
func (*CollateralizeRepay) ProtoMessage()    {}
func (*CollateralizeRepay) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{13}
}

func (m *CollateralizeRepay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollateralizeRepay.Unmarshal(m, b)
}
func (m *CollateralizeRepay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollateralizeRepay.Marshal(b, m, deterministic)
}
func (m *CollateralizeRepay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollateralizeRepay.Merge(m, src)
}
func (m *CollateralizeRepay) XXX_Size() int {
	return xxx_messageInfo_CollateralizeRepay.Size(m)
}
func (m *CollateralizeRepay) XXX_DiscardUnknown() {
	xxx_messageInfo_CollateralizeRepay.DiscardUnknown(m)
}

var xxx_messageInfo_CollateralizeRepay proto.InternalMessageInfo

func (m *CollateralizeRepay) GetCollateralizeId() string {
	if m != nil {
		return m.CollateralizeId
	}
	return ""
}

func (m *CollateralizeRepay) GetRecordId() string {
	if m != nil {
		return m.RecordId
	}
	return ""
}

// 追加抵押物
type CollateralizeAppend struct {
	CollateralizeId      string   `protobuf:"bytes,1,opt,name=collateralizeId,proto3" json:"collateralizeId,omitempty"`
	RecordId             string   `protobuf:"bytes,2,opt,name=recordId,proto3" json:"recordId,omitempty"`
	CollateralValue      int64    `protobuf:"varint,3,opt,name=collateralValue,proto3" json:"collateralValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollateralizeAppend) Reset()         { *m = CollateralizeAppend{} }
func (m *CollateralizeAppend) String() string { return proto.CompactTextString(m) }
func (*CollateralizeAppend) ProtoMessage()    {}
func (*CollateralizeAppend) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{14}
}

func (m *CollateralizeAppend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollateralizeAppend.Unmarshal(m, b)
}
func (m *CollateralizeAppend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollateralizeAppend.Marshal(b, m, deterministic)
}
func (m *CollateralizeAppend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollateralizeAppend.Merge(m, src)
}
func (m *CollateralizeAppend) XXX_Size() int {
	return xxx_messageInfo_CollateralizeAppend.Size(m)
}
func (m *CollateralizeAppend) XXX_DiscardUnknown() {
	xxx_messageInfo_CollateralizeAppend.DiscardUnknown(m)
}

var xxx_messageInfo_CollateralizeAppend proto.InternalMessageInfo

func (m *CollateralizeAppend) GetCollateralizeId() string {
	if m != nil {
		return m.CollateralizeId
	}
	return ""
}

func (m *CollateralizeAppend) GetRecordId() string {
	if m != nil {
		return m.RecordId
	}
	return ""
}

func (m *CollateralizeAppend) GetCollateralValue() int64 {
	if m != nil {
		return m.CollateralValue
	}
	return 0
}

// 喂价
type CollateralizeFeed struct {
	CollType             int32    `protobuf:"varint,1,opt,name=collType,proto3" json:"collType,omitempty"`
	Price                []int64  `protobuf:"varint,2,rep,packed,name=price,proto3" json:"price,omitempty"`
	Volume               []int64  `protobuf:"varint,3,rep,packed,name=volume,proto3" json:"volume,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollateralizeFeed) Reset()         { *m = CollateralizeFeed{} }
func (m *CollateralizeFeed) String() string { return proto.CompactTextString(m) }
func (*CollateralizeFeed) ProtoMessage()    {}
func (*CollateralizeFeed) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{15}
}

func (m *CollateralizeFeed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollateralizeFeed.Unmarshal(m, b)
}
func (m *CollateralizeFeed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollateralizeFeed.Marshal(b, m, deterministic)
}
func (m *CollateralizeFeed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollateralizeFeed.Merge(m, src)
}
func (m *CollateralizeFeed) XXX_Size() int {
	return xxx_messageInfo_CollateralizeFeed.Size(m)
}
func (m *CollateralizeFeed) XXX_DiscardUnknown() {
	xxx_messageInfo_CollateralizeFeed.DiscardUnknown(m)
}

var xxx_messageInfo_CollateralizeFeed proto.InternalMessageInfo

func (m *CollateralizeFeed) GetCollType() int32 {
	if m != nil {
		return m.CollType
	}
	return 0
}

func (m *CollateralizeFeed) GetPrice() []int64 {
	if m != nil {
		return m.Price
	}
	return nil
}

func (m *CollateralizeFeed) GetVolume() []int64 {
	if m != nil {
		return m.Volume
	}
	return nil
}

// 收回
type CollateralizeRetrieve struct {
	CollateralizeId      string   `protobuf:"bytes,1,opt,name=collateralizeId,proto3" json:"collateralizeId,omitempty"`
	Balance              int64    `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollateralizeRetrieve) Reset()         { *m = CollateralizeRetrieve{} }
func (m *CollateralizeRetrieve) String() string { return proto.CompactTextString(m) }
func (*CollateralizeRetrieve) ProtoMessage()    {}
func (*CollateralizeRetrieve) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{16}
}

func (m *CollateralizeRetrieve) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollateralizeRetrieve.Unmarshal(m, b)
}
func (m *CollateralizeRetrieve) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollateralizeRetrieve.Marshal(b, m, deterministic)
}
func (m *CollateralizeRetrieve) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollateralizeRetrieve.Merge(m, src)
}
func (m *CollateralizeRetrieve) XXX_Size() int {
	return xxx_messageInfo_CollateralizeRetrieve.Size(m)
}
func (m *CollateralizeRetrieve) XXX_DiscardUnknown() {
	xxx_messageInfo_CollateralizeRetrieve.DiscardUnknown(m)
}

var xxx_messageInfo_CollateralizeRetrieve proto.InternalMessageInfo

func (m *CollateralizeRetrieve) GetCollateralizeId() string {
	if m != nil {
		return m.CollateralizeId
	}
	return ""
}

func (m *CollateralizeRetrieve) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

// exec_local 放贷信息
type ReceiptCollateralize struct {
	CollateralizeId      string   `protobuf:"bytes,1,opt,name=collateralizeId,proto3" json:"collateralizeId,omitempty"`
	AccountAddr          string   `protobuf:"bytes,3,opt,name=accountAddr,proto3" json:"accountAddr,omitempty"`
	RecordId             string   `protobuf:"bytes,4,opt,name=recordId,proto3" json:"recordId,omitempty"`
	Status               int32    `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiptCollateralize) Reset()         { *m = ReceiptCollateralize{} }
func (m *ReceiptCollateralize) String() string { return proto.CompactTextString(m) }
func (*ReceiptCollateralize) ProtoMessage()    {}
func (*ReceiptCollateralize) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{17}
}

func (m *ReceiptCollateralize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptCollateralize.Unmarshal(m, b)
}
func (m *ReceiptCollateralize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptCollateralize.Marshal(b, m, deterministic)
}
func (m *ReceiptCollateralize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptCollateralize.Merge(m, src)
}
func (m *ReceiptCollateralize) XXX_Size() int {
	return xxx_messageInfo_ReceiptCollateralize.Size(m)
}
func (m *ReceiptCollateralize) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptCollateralize.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptCollateralize proto.InternalMessageInfo

func (m *ReceiptCollateralize) GetCollateralizeId() string {
	if m != nil {
		return m.CollateralizeId
	}
	return ""
}

func (m *ReceiptCollateralize) GetAccountAddr() string {
	if m != nil {
		return m.AccountAddr
	}
	return ""
}

func (m *ReceiptCollateralize) GetRecordId() string {
	if m != nil {
		return m.RecordId
	}
	return ""
}

func (m *ReceiptCollateralize) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// exec_local 放贷记录信息列表
type CollateralizeRecords struct {
	Records              []*ReceiptCollateralize `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *CollateralizeRecords) Reset()         { *m = CollateralizeRecords{} }
func (m *CollateralizeRecords) String() string { return proto.CompactTextString(m) }
func (*CollateralizeRecords) ProtoMessage()    {}
func (*CollateralizeRecords) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{18}
}

func (m *CollateralizeRecords) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollateralizeRecords.Unmarshal(m, b)
}
func (m *CollateralizeRecords) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollateralizeRecords.Marshal(b, m, deterministic)
}
func (m *CollateralizeRecords) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollateralizeRecords.Merge(m, src)
}
func (m *CollateralizeRecords) XXX_Size() int {
	return xxx_messageInfo_CollateralizeRecords.Size(m)
}
func (m *CollateralizeRecords) XXX_DiscardUnknown() {
	xxx_messageInfo_CollateralizeRecords.DiscardUnknown(m)
}

var xxx_messageInfo_CollateralizeRecords proto.InternalMessageInfo

func (m *CollateralizeRecords) GetRecords() []*ReceiptCollateralize {
	if m != nil {
		return m.Records
	}
	return nil
}

// 根据ID查询一期放贷信息
type ReqCollateralizeInfo struct {
	CollateralizeId      string   `protobuf:"bytes,1,opt,name=collateralizeId,proto3" json:"collateralizeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCollateralizeInfo) Reset()         { *m = ReqCollateralizeInfo{} }
func (m *ReqCollateralizeInfo) String() string { return proto.CompactTextString(m) }
func (*ReqCollateralizeInfo) ProtoMessage()    {}
func (*ReqCollateralizeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{19}
}

func (m *ReqCollateralizeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCollateralizeInfo.Unmarshal(m, b)
}
func (m *ReqCollateralizeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCollateralizeInfo.Marshal(b, m, deterministic)
}
func (m *ReqCollateralizeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCollateralizeInfo.Merge(m, src)
}
func (m *ReqCollateralizeInfo) XXX_Size() int {
	return xxx_messageInfo_ReqCollateralizeInfo.Size(m)
}
func (m *ReqCollateralizeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCollateralizeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCollateralizeInfo proto.InternalMessageInfo

func (m *ReqCollateralizeInfo) GetCollateralizeId() string {
	if m != nil {
		return m.CollateralizeId
	}
	return ""
}

// 返回一期放贷信息
type RepCollateralizeCurrentInfo struct {
	Status               int32                `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	TotalBalance         int64                `protobuf:"varint,2,opt,name=totalBalance,proto3" json:"totalBalance,omitempty"`
	DebtCeiling          int64                `protobuf:"varint,3,opt,name=debtCeiling,proto3" json:"debtCeiling,omitempty"`
	LiquidationRatio     int64                `protobuf:"varint,4,opt,name=liquidationRatio,proto3" json:"liquidationRatio,omitempty"`
	StabilityFeeRatio    int64                `protobuf:"varint,5,opt,name=stabilityFeeRatio,proto3" json:"stabilityFeeRatio,omitempty"`
	CreateAddr           string               `protobuf:"bytes,6,opt,name=createAddr,proto3" json:"createAddr,omitempty"`
	Balance              int64                `protobuf:"varint,7,opt,name=balance,proto3" json:"balance,omitempty"`
	Period               int64                `protobuf:"varint,8,opt,name=period,proto3" json:"period,omitempty"`
	CollateralizeId      string               `protobuf:"bytes,9,opt,name=collateralizeId,proto3" json:"collateralizeId,omitempty"`
	CollBalance          int64                `protobuf:"varint,10,opt,name=collBalance,proto3" json:"collBalance,omitempty"`
	Records              []*QueryBorrowRecord `protobuf:"bytes,11,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RepCollateralizeCurrentInfo) Reset()         { *m = RepCollateralizeCurrentInfo{} }
func (m *RepCollateralizeCurrentInfo) String() string { return proto.CompactTextString(m) }
func (*RepCollateralizeCurrentInfo) ProtoMessage()    {}
func (*RepCollateralizeCurrentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{20}
}

func (m *RepCollateralizeCurrentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepCollateralizeCurrentInfo.Unmarshal(m, b)
}
func (m *RepCollateralizeCurrentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepCollateralizeCurrentInfo.Marshal(b, m, deterministic)
}
func (m *RepCollateralizeCurrentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepCollateralizeCurrentInfo.Merge(m, src)
}
func (m *RepCollateralizeCurrentInfo) XXX_Size() int {
	return xxx_messageInfo_RepCollateralizeCurrentInfo.Size(m)
}
func (m *RepCollateralizeCurrentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RepCollateralizeCurrentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RepCollateralizeCurrentInfo proto.InternalMessageInfo

func (m *RepCollateralizeCurrentInfo) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *RepCollateralizeCurrentInfo) GetTotalBalance() int64 {
	if m != nil {
		return m.TotalBalance
	}
	return 0
}

func (m *RepCollateralizeCurrentInfo) GetDebtCeiling() int64 {
	if m != nil {
		return m.DebtCeiling
	}
	return 0
}

func (m *RepCollateralizeCurrentInfo) GetLiquidationRatio() int64 {
	if m != nil {
		return m.LiquidationRatio
	}
	return 0
}

func (m *RepCollateralizeCurrentInfo) GetStabilityFeeRatio() int64 {
	if m != nil {
		return m.StabilityFeeRatio
	}
	return 0
}

func (m *RepCollateralizeCurrentInfo) GetCreateAddr() string {
	if m != nil {
		return m.CreateAddr
	}
	return ""
}

func (m *RepCollateralizeCurrentInfo) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *RepCollateralizeCurrentInfo) GetPeriod() int64 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *RepCollateralizeCurrentInfo) GetCollateralizeId() string {
	if m != nil {
		return m.CollateralizeId
	}
	return ""
}

func (m *RepCollateralizeCurrentInfo) GetCollBalance() int64 {
	if m != nil {
		return m.CollBalance
	}
	return 0
}

func (m *RepCollateralizeCurrentInfo) GetRecords() []*QueryBorrowRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

// 根据ID列表查询多期放贷信息
type ReqCollateralizeInfos struct {
	CollateralizeIds     []string `protobuf:"bytes,1,rep,name=collateralizeIds,proto3" json:"collateralizeIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCollateralizeInfos) Reset()         { *m = ReqCollateralizeInfos{} }
func (m *ReqCollateralizeInfos) String() string { return proto.CompactTextString(m) }
func (*ReqCollateralizeInfos) ProtoMessage()    {}
func (*ReqCollateralizeInfos) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{21}
}

func (m *ReqCollateralizeInfos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCollateralizeInfos.Unmarshal(m, b)
}
func (m *ReqCollateralizeInfos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCollateralizeInfos.Marshal(b, m, deterministic)
}
func (m *ReqCollateralizeInfos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCollateralizeInfos.Merge(m, src)
}
func (m *ReqCollateralizeInfos) XXX_Size() int {
	return xxx_messageInfo_ReqCollateralizeInfos.Size(m)
}
func (m *ReqCollateralizeInfos) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCollateralizeInfos.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCollateralizeInfos proto.InternalMessageInfo

func (m *ReqCollateralizeInfos) GetCollateralizeIds() []string {
	if m != nil {
		return m.CollateralizeIds
	}
	return nil
}

// 返回多期放贷信息
type RepCollateralizeCurrentInfos struct {
	Infos                []*RepCollateralizeCurrentInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *RepCollateralizeCurrentInfos) Reset()         { *m = RepCollateralizeCurrentInfos{} }
func (m *RepCollateralizeCurrentInfos) String() string { return proto.CompactTextString(m) }
func (*RepCollateralizeCurrentInfos) ProtoMessage()    {}
func (*RepCollateralizeCurrentInfos) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{22}
}

func (m *RepCollateralizeCurrentInfos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepCollateralizeCurrentInfos.Unmarshal(m, b)
}
func (m *RepCollateralizeCurrentInfos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepCollateralizeCurrentInfos.Marshal(b, m, deterministic)
}
func (m *RepCollateralizeCurrentInfos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepCollateralizeCurrentInfos.Merge(m, src)
}
func (m *RepCollateralizeCurrentInfos) XXX_Size() int {
	return xxx_messageInfo_RepCollateralizeCurrentInfos.Size(m)
}
func (m *RepCollateralizeCurrentInfos) XXX_DiscardUnknown() {
	xxx_messageInfo_RepCollateralizeCurrentInfos.DiscardUnknown(m)
}

var xxx_messageInfo_RepCollateralizeCurrentInfos proto.InternalMessageInfo

func (m *RepCollateralizeCurrentInfos) GetInfos() []*RepCollateralizeCurrentInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

// 根据放贷状态查询
type ReqCollateralizeByStatus struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	CollID               string   `protobuf:"bytes,2,opt,name=collID,proto3" json:"collID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCollateralizeByStatus) Reset()         { *m = ReqCollateralizeByStatus{} }
func (m *ReqCollateralizeByStatus) String() string { return proto.CompactTextString(m) }
func (*ReqCollateralizeByStatus) ProtoMessage()    {}
func (*ReqCollateralizeByStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{23}
}

func (m *ReqCollateralizeByStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCollateralizeByStatus.Unmarshal(m, b)
}
func (m *ReqCollateralizeByStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCollateralizeByStatus.Marshal(b, m, deterministic)
}
func (m *ReqCollateralizeByStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCollateralizeByStatus.Merge(m, src)
}
func (m *ReqCollateralizeByStatus) XXX_Size() int {
	return xxx_messageInfo_ReqCollateralizeByStatus.Size(m)
}
func (m *ReqCollateralizeByStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCollateralizeByStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCollateralizeByStatus proto.InternalMessageInfo

func (m *ReqCollateralizeByStatus) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ReqCollateralizeByStatus) GetCollID() string {
	if m != nil {
		return m.CollID
	}
	return ""
}

// 根据用户地址查询
type ReqCollateralizeByAddr struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	CollID               string   `protobuf:"bytes,3,opt,name=collID,proto3" json:"collID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCollateralizeByAddr) Reset()         { *m = ReqCollateralizeByAddr{} }
func (m *ReqCollateralizeByAddr) String() string { return proto.CompactTextString(m) }
func (*ReqCollateralizeByAddr) ProtoMessage()    {}
func (*ReqCollateralizeByAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{24}
}

func (m *ReqCollateralizeByAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCollateralizeByAddr.Unmarshal(m, b)
}
func (m *ReqCollateralizeByAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCollateralizeByAddr.Marshal(b, m, deterministic)
}
func (m *ReqCollateralizeByAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCollateralizeByAddr.Merge(m, src)
}
func (m *ReqCollateralizeByAddr) XXX_Size() int {
	return xxx_messageInfo_ReqCollateralizeByAddr.Size(m)
}
func (m *ReqCollateralizeByAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCollateralizeByAddr.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCollateralizeByAddr proto.InternalMessageInfo

func (m *ReqCollateralizeByAddr) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *ReqCollateralizeByAddr) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ReqCollateralizeByAddr) GetCollID() string {
	if m != nil {
		return m.CollID
	}
	return ""
}

// 返回放贷ID列表
type RepCollateralizeIDs struct {
	IDs                  []string `protobuf:"bytes,1,rep,name=IDs,proto3" json:"IDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepCollateralizeIDs) Reset()         { *m = RepCollateralizeIDs{} }
func (m *RepCollateralizeIDs) String() string { return proto.CompactTextString(m) }
func (*RepCollateralizeIDs) ProtoMessage()    {}
func (*RepCollateralizeIDs) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{25}
}

func (m *RepCollateralizeIDs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepCollateralizeIDs.Unmarshal(m, b)
}
func (m *RepCollateralizeIDs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepCollateralizeIDs.Marshal(b, m, deterministic)
}
func (m *RepCollateralizeIDs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepCollateralizeIDs.Merge(m, src)
}
func (m *RepCollateralizeIDs) XXX_Size() int {
	return xxx_messageInfo_RepCollateralizeIDs.Size(m)
}
func (m *RepCollateralizeIDs) XXX_DiscardUnknown() {
	xxx_messageInfo_RepCollateralizeIDs.DiscardUnknown(m)
}

var xxx_messageInfo_RepCollateralizeIDs proto.InternalMessageInfo

func (m *RepCollateralizeIDs) GetIDs() []string {
	if m != nil {
		return m.IDs
	}
	return nil
}

// 根据地址和借贷ID混合查询具体借贷记录
type ReqCollateralizeRecordByAddr struct {
	CollateralizeId      string   `protobuf:"bytes,1,opt,name=collateralizeId,proto3" json:"collateralizeId,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Status               int32    `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	RecordId             string   `protobuf:"bytes,4,opt,name=recordId,proto3" json:"recordId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCollateralizeRecordByAddr) Reset()         { *m = ReqCollateralizeRecordByAddr{} }
func (m *ReqCollateralizeRecordByAddr) String() string { return proto.CompactTextString(m) }
func (*ReqCollateralizeRecordByAddr) ProtoMessage()    {}
func (*ReqCollateralizeRecordByAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{26}
}

func (m *ReqCollateralizeRecordByAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCollateralizeRecordByAddr.Unmarshal(m, b)
}
func (m *ReqCollateralizeRecordByAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCollateralizeRecordByAddr.Marshal(b, m, deterministic)
}
func (m *ReqCollateralizeRecordByAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCollateralizeRecordByAddr.Merge(m, src)
}
func (m *ReqCollateralizeRecordByAddr) XXX_Size() int {
	return xxx_messageInfo_ReqCollateralizeRecordByAddr.Size(m)
}
func (m *ReqCollateralizeRecordByAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCollateralizeRecordByAddr.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCollateralizeRecordByAddr proto.InternalMessageInfo

func (m *ReqCollateralizeRecordByAddr) GetCollateralizeId() string {
	if m != nil {
		return m.CollateralizeId
	}
	return ""
}

func (m *ReqCollateralizeRecordByAddr) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *ReqCollateralizeRecordByAddr) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ReqCollateralizeRecordByAddr) GetRecordId() string {
	if m != nil {
		return m.RecordId
	}
	return ""
}

// 根据状态和借贷ID混合查询具体借贷记录
type ReqCollateralizeRecordByStatus struct {
	CollateralizeId      string   `protobuf:"bytes,1,opt,name=collateralizeId,proto3" json:"collateralizeId,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	RecordId             string   `protobuf:"bytes,3,opt,name=recordId,proto3" json:"recordId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCollateralizeRecordByStatus) Reset()         { *m = ReqCollateralizeRecordByStatus{} }
func (m *ReqCollateralizeRecordByStatus) String() string { return proto.CompactTextString(m) }
func (*ReqCollateralizeRecordByStatus) ProtoMessage()    {}
func (*ReqCollateralizeRecordByStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{27}
}

func (m *ReqCollateralizeRecordByStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCollateralizeRecordByStatus.Unmarshal(m, b)
}
func (m *ReqCollateralizeRecordByStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCollateralizeRecordByStatus.Marshal(b, m, deterministic)
}
func (m *ReqCollateralizeRecordByStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCollateralizeRecordByStatus.Merge(m, src)
}
func (m *ReqCollateralizeRecordByStatus) XXX_Size() int {
	return xxx_messageInfo_ReqCollateralizeRecordByStatus.Size(m)
}
func (m *ReqCollateralizeRecordByStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCollateralizeRecordByStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCollateralizeRecordByStatus proto.InternalMessageInfo

func (m *ReqCollateralizeRecordByStatus) GetCollateralizeId() string {
	if m != nil {
		return m.CollateralizeId
	}
	return ""
}

func (m *ReqCollateralizeRecordByStatus) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ReqCollateralizeRecordByStatus) GetRecordId() string {
	if m != nil {
		return m.RecordId
	}
	return ""
}

// 返回借贷记录
type RepCollateralizeRecords struct {
	Records              []*QueryBorrowRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RepCollateralizeRecords) Reset()         { *m = RepCollateralizeRecords{} }
func (m *RepCollateralizeRecords) String() string { return proto.CompactTextString(m) }
func (*RepCollateralizeRecords) ProtoMessage()    {}
func (*RepCollateralizeRecords) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{28}
}

func (m *RepCollateralizeRecords) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepCollateralizeRecords.Unmarshal(m, b)
}
func (m *RepCollateralizeRecords) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepCollateralizeRecords.Marshal(b, m, deterministic)
}
func (m *RepCollateralizeRecords) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepCollateralizeRecords.Merge(m, src)
}
func (m *RepCollateralizeRecords) XXX_Size() int {
	return xxx_messageInfo_RepCollateralizeRecords.Size(m)
}
func (m *RepCollateralizeRecords) XXX_DiscardUnknown() {
	xxx_messageInfo_RepCollateralizeRecords.DiscardUnknown(m)
}

var xxx_messageInfo_RepCollateralizeRecords proto.InternalMessageInfo

func (m *RepCollateralizeRecords) GetRecords() []*QueryBorrowRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

// 精确查找借贷记录
type ReqCollateralizeRecord struct {
	CollateralizeId      string   `protobuf:"bytes,1,opt,name=collateralizeId,proto3" json:"collateralizeId,omitempty"`
	RecordId             string   `protobuf:"bytes,2,opt,name=recordId,proto3" json:"recordId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCollateralizeRecord) Reset()         { *m = ReqCollateralizeRecord{} }
func (m *ReqCollateralizeRecord) String() string { return proto.CompactTextString(m) }
func (*ReqCollateralizeRecord) ProtoMessage()    {}
func (*ReqCollateralizeRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{29}
}

func (m *ReqCollateralizeRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCollateralizeRecord.Unmarshal(m, b)
}
func (m *ReqCollateralizeRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCollateralizeRecord.Marshal(b, m, deterministic)
}
func (m *ReqCollateralizeRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCollateralizeRecord.Merge(m, src)
}
func (m *ReqCollateralizeRecord) XXX_Size() int {
	return xxx_messageInfo_ReqCollateralizeRecord.Size(m)
}
func (m *ReqCollateralizeRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCollateralizeRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCollateralizeRecord proto.InternalMessageInfo

func (m *ReqCollateralizeRecord) GetCollateralizeId() string {
	if m != nil {
		return m.CollateralizeId
	}
	return ""
}

func (m *ReqCollateralizeRecord) GetRecordId() string {
	if m != nil {
		return m.RecordId
	}
	return ""
}

// 返回借贷记录
type RepCollateralizeRecord struct {
	Record               *QueryBorrowRecord `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RepCollateralizeRecord) Reset()         { *m = RepCollateralizeRecord{} }
func (m *RepCollateralizeRecord) String() string { return proto.CompactTextString(m) }
func (*RepCollateralizeRecord) ProtoMessage()    {}
func (*RepCollateralizeRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{30}
}

func (m *RepCollateralizeRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepCollateralizeRecord.Unmarshal(m, b)
}
func (m *RepCollateralizeRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepCollateralizeRecord.Marshal(b, m, deterministic)
}
func (m *RepCollateralizeRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepCollateralizeRecord.Merge(m, src)
}
func (m *RepCollateralizeRecord) XXX_Size() int {
	return xxx_messageInfo_RepCollateralizeRecord.Size(m)
}
func (m *RepCollateralizeRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_RepCollateralizeRecord.DiscardUnknown(m)
}

var xxx_messageInfo_RepCollateralizeRecord proto.InternalMessageInfo

func (m *RepCollateralizeRecord) GetRecord() *QueryBorrowRecord {
	if m != nil {
		return m.Record
	}
	return nil
}

// 返回放贷配置
type RepCollateralizeConfig struct {
	DebtCeiling          int64    `protobuf:"varint,1,opt,name=debtCeiling,proto3" json:"debtCeiling,omitempty"`
	LiquidationRatio     int64    `protobuf:"varint,2,opt,name=liquidationRatio,proto3" json:"liquidationRatio,omitempty"`
	StabilityFeeRatio    int64    `protobuf:"varint,3,opt,name=stabilityFeeRatio,proto3" json:"stabilityFeeRatio,omitempty"`
	Period               int64    `protobuf:"varint,4,opt,name=period,proto3" json:"period,omitempty"`
	TotalBalance         int64    `protobuf:"varint,5,opt,name=totalBalance,proto3" json:"totalBalance,omitempty"`
	Balance              int64    `protobuf:"varint,6,opt,name=balance,proto3" json:"balance,omitempty"`
	CurrentTime          int64    `protobuf:"varint,7,opt,name=currentTime,proto3" json:"currentTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepCollateralizeConfig) Reset()         { *m = RepCollateralizeConfig{} }
func (m *RepCollateralizeConfig) String() string { return proto.CompactTextString(m) }
func (*RepCollateralizeConfig) ProtoMessage()    {}
func (*RepCollateralizeConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{31}
}

func (m *RepCollateralizeConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepCollateralizeConfig.Unmarshal(m, b)
}
func (m *RepCollateralizeConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepCollateralizeConfig.Marshal(b, m, deterministic)
}
func (m *RepCollateralizeConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepCollateralizeConfig.Merge(m, src)
}
func (m *RepCollateralizeConfig) XXX_Size() int {
	return xxx_messageInfo_RepCollateralizeConfig.Size(m)
}
func (m *RepCollateralizeConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_RepCollateralizeConfig.DiscardUnknown(m)
}

var xxx_messageInfo_RepCollateralizeConfig proto.InternalMessageInfo

func (m *RepCollateralizeConfig) GetDebtCeiling() int64 {
	if m != nil {
		return m.DebtCeiling
	}
	return 0
}

func (m *RepCollateralizeConfig) GetLiquidationRatio() int64 {
	if m != nil {
		return m.LiquidationRatio
	}
	return 0
}

func (m *RepCollateralizeConfig) GetStabilityFeeRatio() int64 {
	if m != nil {
		return m.StabilityFeeRatio
	}
	return 0
}

func (m *RepCollateralizeConfig) GetPeriod() int64 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *RepCollateralizeConfig) GetTotalBalance() int64 {
	if m != nil {
		return m.TotalBalance
	}
	return 0
}

func (m *RepCollateralizeConfig) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *RepCollateralizeConfig) GetCurrentTime() int64 {
	if m != nil {
		return m.CurrentTime
	}
	return 0
}

// 返回最新抵押物价格
type RepCollateralizePrice struct {
	Price                int64    `protobuf:"varint,1,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepCollateralizePrice) Reset()         { *m = RepCollateralizePrice{} }
func (m *RepCollateralizePrice) String() string { return proto.CompactTextString(m) }
func (*RepCollateralizePrice) ProtoMessage()    {}
func (*RepCollateralizePrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{32}
}

func (m *RepCollateralizePrice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepCollateralizePrice.Unmarshal(m, b)
}
func (m *RepCollateralizePrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepCollateralizePrice.Marshal(b, m, deterministic)
}
func (m *RepCollateralizePrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepCollateralizePrice.Merge(m, src)
}
func (m *RepCollateralizePrice) XXX_Size() int {
	return xxx_messageInfo_RepCollateralizePrice.Size(m)
}
func (m *RepCollateralizePrice) XXX_DiscardUnknown() {
	xxx_messageInfo_RepCollateralizePrice.DiscardUnknown(m)
}

var xxx_messageInfo_RepCollateralizePrice proto.InternalMessageInfo

func (m *RepCollateralizePrice) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

// 返回用户借贷总额
type RepCollateralizeUserBalance struct {
	Balance              int64    `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepCollateralizeUserBalance) Reset()         { *m = RepCollateralizeUserBalance{} }
func (m *RepCollateralizeUserBalance) String() string { return proto.CompactTextString(m) }
func (*RepCollateralizeUserBalance) ProtoMessage()    {}
func (*RepCollateralizeUserBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{33}
}

func (m *RepCollateralizeUserBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepCollateralizeUserBalance.Unmarshal(m, b)
}
func (m *RepCollateralizeUserBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepCollateralizeUserBalance.Marshal(b, m, deterministic)
}
func (m *RepCollateralizeUserBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepCollateralizeUserBalance.Merge(m, src)
}
func (m *RepCollateralizeUserBalance) XXX_Size() int {
	return xxx_messageInfo_RepCollateralizeUserBalance.Size(m)
}
func (m *RepCollateralizeUserBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_RepCollateralizeUserBalance.DiscardUnknown(m)
}

var xxx_messageInfo_RepCollateralizeUserBalance proto.InternalMessageInfo

func (m *RepCollateralizeUserBalance) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

// 返回后台管理放贷状态
type RepCollateralizeLendStatus struct {
	RecordNum            int64    `protobuf:"varint,1,opt,name=recordNum,proto3" json:"recordNum,omitempty"`
	TotalCollBalance     int64    `protobuf:"varint,2,opt,name=totalCollBalance,proto3" json:"totalCollBalance,omitempty"`
	TotalLendBalance     int64    `protobuf:"varint,3,opt,name=totalLendBalance,proto3" json:"totalLendBalance,omitempty"`
	ConfigBalance        int64    `protobuf:"varint,4,opt,name=configBalance,proto3" json:"configBalance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepCollateralizeLendStatus) Reset()         { *m = RepCollateralizeLendStatus{} }
func (m *RepCollateralizeLendStatus) String() string { return proto.CompactTextString(m) }
func (*RepCollateralizeLendStatus) ProtoMessage()    {}
func (*RepCollateralizeLendStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{34}
}

func (m *RepCollateralizeLendStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepCollateralizeLendStatus.Unmarshal(m, b)
}
func (m *RepCollateralizeLendStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepCollateralizeLendStatus.Marshal(b, m, deterministic)
}
func (m *RepCollateralizeLendStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepCollateralizeLendStatus.Merge(m, src)
}
func (m *RepCollateralizeLendStatus) XXX_Size() int {
	return xxx_messageInfo_RepCollateralizeLendStatus.Size(m)
}
func (m *RepCollateralizeLendStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_RepCollateralizeLendStatus.DiscardUnknown(m)
}

var xxx_messageInfo_RepCollateralizeLendStatus proto.InternalMessageInfo

func (m *RepCollateralizeLendStatus) GetRecordNum() int64 {
	if m != nil {
		return m.RecordNum
	}
	return 0
}

func (m *RepCollateralizeLendStatus) GetTotalCollBalance() int64 {
	if m != nil {
		return m.TotalCollBalance
	}
	return 0
}

func (m *RepCollateralizeLendStatus) GetTotalLendBalance() int64 {
	if m != nil {
		return m.TotalLendBalance
	}
	return 0
}

func (m *RepCollateralizeLendStatus) GetConfigBalance() int64 {
	if m != nil {
		return m.ConfigBalance
	}
	return 0
}

// 返回放贷用户放贷总额
type RepCollateralizeLenderBalance struct {
	TotalLentBalance     int64    `protobuf:"varint,1,opt,name=totalLentBalance,proto3" json:"totalLentBalance,omitempty"`
	TotalLendingBalance  int64    `protobuf:"varint,2,opt,name=totalLendingBalance,proto3" json:"totalLendingBalance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepCollateralizeLenderBalance) Reset()         { *m = RepCollateralizeLenderBalance{} }
func (m *RepCollateralizeLenderBalance) String() string { return proto.CompactTextString(m) }
func (*RepCollateralizeLenderBalance) ProtoMessage()    {}
func (*RepCollateralizeLenderBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_a988fb4a61381972, []int{35}
}

func (m *RepCollateralizeLenderBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepCollateralizeLenderBalance.Unmarshal(m, b)
}
func (m *RepCollateralizeLenderBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepCollateralizeLenderBalance.Marshal(b, m, deterministic)
}
func (m *RepCollateralizeLenderBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepCollateralizeLenderBalance.Merge(m, src)
}
func (m *RepCollateralizeLenderBalance) XXX_Size() int {
	return xxx_messageInfo_RepCollateralizeLenderBalance.Size(m)
}
func (m *RepCollateralizeLenderBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_RepCollateralizeLenderBalance.DiscardUnknown(m)
}

var xxx_messageInfo_RepCollateralizeLenderBalance proto.InternalMessageInfo

func (m *RepCollateralizeLenderBalance) GetTotalLentBalance() int64 {
	if m != nil {
		return m.TotalLentBalance
	}
	return 0
}

func (m *RepCollateralizeLenderBalance) GetTotalLendingBalance() int64 {
	if m != nil {
		return m.TotalLendingBalance
	}
	return 0
}

func init() {
	proto.RegisterType((*Collateralize)(nil), "types.Collateralize")
	proto.RegisterType((*BorrowRecord)(nil), "types.BorrowRecord")
	proto.RegisterType((*QueryBorrowRecord)(nil), "types.QueryBorrowRecord")
	proto.RegisterType((*AssetPriceRecord)(nil), "types.AssetPriceRecord")
	proto.RegisterType((*CollateralizeAction)(nil), "types.CollateralizeAction")
	proto.RegisterType((*CollateralizeManage)(nil), "types.CollateralizeManage")
	proto.RegisterType((*CollateralizeAddr)(nil), "types.CollateralizeAddr")
	proto.RegisterType((*CollateralizeLend)(nil), "types.CollateralizeLend")
	proto.RegisterType((*CollateralizeColler)(nil), "types.CollateralizeColler")
	proto.RegisterType((*CollateralizeTokenItem)(nil), "types.CollateralizeTokenItem")
	proto.RegisterType((*CollateralizeTokenConfig)(nil), "types.CollateralizeTokenConfig")
	proto.RegisterType((*CollateralizeCreate)(nil), "types.CollateralizeCreate")
	proto.RegisterType((*CollateralizeBorrow)(nil), "types.CollateralizeBorrow")
	proto.RegisterType((*CollateralizeRepay)(nil), "types.CollateralizeRepay")
	proto.RegisterType((*CollateralizeAppend)(nil), "types.CollateralizeAppend")
	proto.RegisterType((*CollateralizeFeed)(nil), "types.CollateralizeFeed")
	proto.RegisterType((*CollateralizeRetrieve)(nil), "types.CollateralizeRetrieve")
	proto.RegisterType((*ReceiptCollateralize)(nil), "types.ReceiptCollateralize")
	proto.RegisterType((*CollateralizeRecords)(nil), "types.CollateralizeRecords")
	proto.RegisterType((*ReqCollateralizeInfo)(nil), "types.ReqCollateralizeInfo")
	proto.RegisterType((*RepCollateralizeCurrentInfo)(nil), "types.RepCollateralizeCurrentInfo")
	proto.RegisterType((*ReqCollateralizeInfos)(nil), "types.ReqCollateralizeInfos")
	proto.RegisterType((*RepCollateralizeCurrentInfos)(nil), "types.RepCollateralizeCurrentInfos")
	proto.RegisterType((*ReqCollateralizeByStatus)(nil), "types.ReqCollateralizeByStatus")
	proto.RegisterType((*ReqCollateralizeByAddr)(nil), "types.ReqCollateralizeByAddr")
	proto.RegisterType((*RepCollateralizeIDs)(nil), "types.RepCollateralizeIDs")
	proto.RegisterType((*ReqCollateralizeRecordByAddr)(nil), "types.ReqCollateralizeRecordByAddr")
	proto.RegisterType((*ReqCollateralizeRecordByStatus)(nil), "types.ReqCollateralizeRecordByStatus")
	proto.RegisterType((*RepCollateralizeRecords)(nil), "types.RepCollateralizeRecords")
	proto.RegisterType((*ReqCollateralizeRecord)(nil), "types.ReqCollateralizeRecord")
	proto.RegisterType((*RepCollateralizeRecord)(nil), "types.RepCollateralizeRecord")
	proto.RegisterType((*RepCollateralizeConfig)(nil), "types.RepCollateralizeConfig")
	proto.RegisterType((*RepCollateralizePrice)(nil), "types.RepCollateralizePrice")
	proto.RegisterType((*RepCollateralizeUserBalance)(nil), "types.RepCollateralizeUserBalance")
	proto.RegisterType((*RepCollateralizeLendStatus)(nil), "types.RepCollateralizeLendStatus")
	proto.RegisterType((*RepCollateralizeLenderBalance)(nil), "types.RepCollateralizeLenderBalance")
}

func init() { proto.RegisterFile("collateralize.proto", fileDescriptor_a988fb4a61381972) }

var fileDescriptor_a988fb4a61381972 = []byte{
	// 1484 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x58, 0x5b, 0x6f, 0xdc, 0xc4,
	0x17, 0xaf, 0xd7, 0x7b, 0xc9, 0x9e, 0x4d, 0x7a, 0x99, 0xa4, 0xf9, 0xfb, 0xdf, 0xa6, 0x51, 0x34,
	0xaa, 0x44, 0x84, 0x20, 0x6a, 0xb7, 0xdc, 0x0a, 0x12, 0x22, 0x49, 0xa9, 0xba, 0x55, 0xcb, 0xc5,
	0xb4, 0x08, 0x71, 0x93, 0x1c, 0x7b, 0x1a, 0x2c, 0xbc, 0x6b, 0xd7, 0x9e, 0x0d, 0x2c, 0x12, 0xbc,
	0xc1, 0x0b, 0x3c, 0x20, 0x1e, 0xf8, 0x0a, 0x88, 0x17, 0x9e, 0xf9, 0x32, 0x88, 0x8f, 0xc0, 0x57,
	0x40, 0x33, 0x67, 0xbc, 0xf6, 0x8c, 0xed, 0x64, 0x83, 0x2a, 0x04, 0xbc, 0x44, 0x3b, 0x67, 0x7e,
	0x73, 0x7c, 0xe6, 0xf7, 0x3b, 0x73, 0xe6, 0x4c, 0x60, 0xd5, 0x8f, 0xa3, 0xc8, 0xe3, 0x2c, 0xf5,
	0xa2, 0xf0, 0x0b, 0xb6, 0x93, 0xa4, 0x31, 0x8f, 0x49, 0x87, 0xcf, 0x12, 0x96, 0xd1, 0xdf, 0xdb,
	0xb0, 0xb2, 0x5f, 0x9e, 0x26, 0xdb, 0x70, 0x4e, 0xc3, 0x8f, 0x02, 0xc7, 0xda, 0xb2, 0xb6, 0xfb,
	0xae, 0x69, 0x26, 0x14, 0x96, 0x79, 0xcc, 0xbd, 0x68, 0xcf, 0x8b, 0xbc, 0x89, 0xcf, 0x9c, 0xd6,
	0x96, 0xb5, 0x6d, 0xbb, 0x9a, 0x8d, 0x6c, 0xc1, 0x20, 0x60, 0x07, 0x7c, 0x9f, 0x85, 0x51, 0x38,
	0x39, 0x74, 0x6c, 0x09, 0x29, 0x9b, 0xc8, 0xd3, 0x70, 0x3e, 0x0a, 0x1f, 0x4f, 0xc3, 0xc0, 0xe3,
	0x61, 0x3c, 0x71, 0xc5, 0x5f, 0xa7, 0x2d, 0x61, 0x15, 0x3b, 0x79, 0x06, 0x2e, 0x64, 0xdc, 0x3b,
	0x08, 0xa3, 0x90, 0xcf, 0x6e, 0x33, 0x86, 0xe0, 0x8e, 0x04, 0x57, 0x27, 0xc8, 0x26, 0x80, 0x9f,
	0x32, 0x8f, 0xb3, 0xdd, 0x20, 0x48, 0x9d, 0xae, 0xdc, 0x44, 0xc9, 0x42, 0x1c, 0xe8, 0x1d, 0xa8,
	0xd0, 0x7b, 0xd2, 0x47, 0x3e, 0x24, 0x37, 0x61, 0xe5, 0x20, 0x4e, 0xd3, 0xf8, 0x33, 0x97, 0xf9,
	0x71, 0x1a, 0x64, 0xce, 0xd2, 0x96, 0xbd, 0x3d, 0x18, 0xae, 0xee, 0x48, 0xd2, 0x76, 0xf6, 0x4a,
	0x73, 0xae, 0x8e, 0x24, 0xaf, 0xc0, 0xd9, 0xd1, 0xe4, 0xc8, 0x8b, 0xc2, 0x20, 0x5f, 0xdb, 0x6f,
	0x5e, 0x6b, 0x40, 0xc9, 0x3a, 0x74, 0x33, 0xee, 0xf1, 0x69, 0xe6, 0xc0, 0x96, 0xb5, 0xdd, 0x71,
	0xd5, 0x88, 0xbc, 0x00, 0xeb, 0x82, 0xf9, 0x8c, 0xdf, 0x2b, 0x18, 0x79, 0x2b, 0x0d, 0x7d, 0xe6,
	0x0c, 0x64, 0xe0, 0x0d, 0xb3, 0xc2, 0x5f, 0xc2, 0xd2, 0x30, 0x0e, 0x9c, 0x65, 0x89, 0x53, 0x23,
	0xc9, 0xb9, 0x5c, 0xf1, 0xfa, 0xe7, 0x49, 0x98, 0xb2, 0x07, 0xe1, 0x98, 0x39, 0x2b, 0x8a, 0x73,
	0xc3, 0x2e, 0x14, 0x14, 0xc2, 0xe7, 0x22, 0x9f, 0x45, 0x05, 0x4b, 0x26, 0xb2, 0x01, 0xfd, 0x24,
	0x65, 0xef, 0x60, 0xe0, 0xe7, 0x64, 0xe0, 0x85, 0x81, 0xfe, 0x62, 0xc3, 0x72, 0x79, 0xd3, 0xc2,
	0xa1, 0xe7, 0xfb, 0xf1, 0x74, 0xc2, 0xa5, 0x2e, 0x98, 0x5c, 0x65, 0x93, 0x70, 0x98, 0x71, 0x2f,
	0xe5, 0x32, 0x2e, 0xcc, 0xaa, 0xc2, 0xa0, 0x27, 0xe8, 0xbb, 0x5e, 0x34, 0x65, 0x2a, 0xad, 0x4c,
	0xb3, 0x8e, 0x44, 0xbe, 0xda, 0x26, 0x12, 0x89, 0xda, 0x80, 0xbe, 0xc8, 0x49, 0xf4, 0x86, 0x09,
	0x55, 0x18, 0x8c, 0x14, 0x45, 0x47, 0xdd, 0x4a, 0x8a, 0xce, 0x29, 0x57, 0x12, 0xf6, 0x34, 0x09,
	0xaf, 0xc2, 0x4a, 0x8e, 0x45, 0xbe, 0x97, 0xa4, 0x03, 0xdd, 0x28, 0x52, 0x96, 0x15, 0x92, 0xf4,
	0x25, 0xa4, 0x64, 0xd1, 0xa9, 0x06, 0x83, 0x6a, 0x72, 0x09, 0x96, 0x52, 0xc9, 0xf1, 0x28, 0x90,
	0x89, 0xd1, 0x77, 0xe7, 0xe3, 0xba, 0x63, 0xbd, 0x5c, 0x7b, 0xac, 0xe9, 0x6f, 0x36, 0x5c, 0x78,
	0x7b, 0xca, 0xd2, 0xd9, 0x3f, 0x41, 0xb5, 0x07, 0xf1, 0xa7, 0x6c, 0x22, 0x55, 0xd3, 0x22, 0x95,
	0xe6, 0x3a, 0x7d, 0x3b, 0x0b, 0xe8, 0xdb, 0x5d, 0x44, 0xdf, 0xde, 0x89, 0xfa, 0x2e, 0x1d, 0xaf,
	0x6f, 0xff, 0x64, 0x7d, 0xe1, 0x78, 0x7d, 0x07, 0xc7, 0xe9, 0xbb, 0x7c, 0xb2, 0xbe, 0x2b, 0xf5,
	0xfa, 0x7e, 0x63, 0xc1, 0xf9, 0xdd, 0x2c, 0x63, 0x5c, 0x6e, 0x48, 0xc9, 0xbb, 0x09, 0x80, 0xae,
	0x64, 0x60, 0x16, 0x06, 0x56, 0x58, 0xc4, 0xa7, 0x0f, 0xf8, 0x0c, 0xa9, 0x41, 0x6d, 0xe7, 0x63,
	0x9c, 0xf3, 0x71, 0xce, 0xce, 0xe7, 0xfc, 0xf9, 0x1c, 0xe3, 0x9f, 0x94, 0xcf, 0xde, 0x7c, 0x4c,
	0xbf, 0x6d, 0xc3, 0xaa, 0x76, 0xf7, 0xec, 0xfa, 0x82, 0x67, 0xf2, 0x1c, 0x74, 0xb1, 0x4a, 0xcb,
	0x38, 0x06, 0xc3, 0x4b, 0xaa, 0x74, 0x6a, 0xd8, 0x7d, 0x89, 0xb8, 0x73, 0xc6, 0x55, 0x58, 0xb1,
	0x0a, 0x2b, 0xb1, 0x8c, 0xaf, 0x61, 0x15, 0xa6, 0xb4, 0x58, 0x85, 0x58, 0x72, 0x1d, 0x3a, 0x29,
	0x4b, 0xbc, 0x99, 0x0c, 0x7c, 0x30, 0xfc, 0x7f, 0xdd, 0x22, 0x57, 0x00, 0xee, 0x9c, 0x71, 0x11,
	0x29, 0x3e, 0xe4, 0x25, 0x09, 0x9b, 0x04, 0x72, 0x43, 0x0d, 0x1f, 0xda, 0x95, 0x08, 0xf1, 0x21,
	0xc4, 0x92, 0x1d, 0x68, 0x3f, 0x62, 0x2c, 0x90, 0x09, 0x3a, 0x18, 0x3a, 0x75, 0x6b, 0x6e, 0x33,
	0x26, 0x56, 0x48, 0x1c, 0x79, 0x59, 0x68, 0xcd, 0xd3, 0x90, 0x1d, 0x61, 0xc2, 0x0e, 0x86, 0x1b,
	0xf5, 0xb1, 0x21, 0xe6, 0xce, 0x19, 0x77, 0x8e, 0x17, 0x11, 0x8e, 0xbd, 0x89, 0x77, 0x88, 0x59,
	0xdc, 0x10, 0xe1, 0x7d, 0x89, 0x10, 0x11, 0x22, 0x56, 0xd2, 0x1e, 0x47, 0x11, 0x4b, 0x65, 0x66,
	0x37, 0xd1, 0x2e, 0x11, 0x92, 0x76, 0xf9, 0x4b, 0xec, 0x2b, 0x12, 0x5c, 0xf4, 0x9b, 0xf7, 0x75,
	0x0f, 0x99, 0x90, 0x38, 0x72, 0x16, 0x5a, 0x7c, 0xa6, 0x4a, 0x57, 0x8b, 0xcf, 0xf6, 0x7a, 0xd0,
	0x39, 0x12, 0x87, 0x90, 0xfe, 0x61, 0x19, 0xd9, 0x80, 0x01, 0x9a, 0x1d, 0x84, 0xb5, 0x58, 0x07,
	0xd1, 0x3a, 0x4d, 0x07, 0x61, 0x37, 0x75, 0x10, 0xc5, 0xfd, 0xd9, 0xd6, 0xee, 0x4f, 0xb3, 0xf3,
	0xe9, 0xd4, 0x77, 0x3e, 0xfe, 0x34, 0x4d, 0xd9, 0x04, 0x0b, 0x62, 0x57, 0xdd, 0x9b, 0x85, 0x89,
	0xde, 0x80, 0x0b, 0x7a, 0xce, 0x88, 0x2a, 0xba, 0x09, 0x90, 0x4d, 0x13, 0x96, 0x8a, 0x41, 0xe6,
	0x58, 0x5b, 0xb6, 0x68, 0x5a, 0x0a, 0x0b, 0xfd, 0xd9, 0x32, 0x56, 0x09, 0x76, 0x2b, 0x01, 0x59,
	0x35, 0x01, 0xfd, 0xed, 0x34, 0xd1, 0x1f, 0x4c, 0x49, 0x31, 0x7b, 0x64, 0x63, 0x26, 0x7f, 0x95,
	0xae, 0x92, 0x92, 0xa5, 0xdc, 0x98, 0xb5, 0xf4, 0xc6, 0xec, 0x3a, 0xb4, 0x43, 0xce, 0xc6, 0xea,
	0xb4, 0x5e, 0xa9, 0xcb, 0x36, 0x79, 0x35, 0x8c, 0x38, 0x1b, 0xbb, 0x12, 0x2a, 0x12, 0x2e, 0x4e,
	0xd4, 0x0d, 0xd2, 0x8a, 0x13, 0xfa, 0x2a, 0xac, 0xd7, 0xe3, 0xc9, 0x1a, 0x74, 0xb8, 0xbc, 0x6e,
	0x30, 0x22, 0x1c, 0x88, 0xf5, 0x61, 0xa0, 0xe2, 0x68, 0x85, 0x01, 0x7d, 0x13, 0x9c, 0xea, 0xfa,
	0xfd, 0x78, 0xf2, 0x28, 0x3c, 0x24, 0x37, 0xa0, 0x23, 0xbe, 0x89, 0xba, 0x9d, 0x18, 0x1f, 0x62,
	0xe9, 0x4d, 0x93, 0x24, 0xac, 0x67, 0x0b, 0x48, 0x4a, 0x1f, 0x1a, 0x4b, 0xb1, 0xbc, 0x9d, 0xa2,
	0x85, 0x5f, 0x53, 0xa7, 0x4f, 0xed, 0x4f, 0x1d, 0xc5, 0xf7, 0x81, 0x54, 0x0b, 0xe0, 0x29, 0xbc,
	0x96, 0xef, 0xa9, 0x96, 0x7e, 0x4f, 0xd1, 0xaf, 0xcd, 0x9c, 0xc0, 0x4a, 0xf9, 0x64, 0xbc, 0x2f,
	0xde, 0x65, 0xd0, 0x8f, 0x8c, 0x63, 0x24, 0x8a, 0xaf, 0x70, 0x2d, 0x70, 0x0f, 0x66, 0x09, 0xf2,
	0xdd, 0x71, 0xe7, 0x63, 0x41, 0x55, 0xa2, 0xae, 0x3f, 0x5b, 0x50, 0x95, 0xe4, 0xed, 0xc0, 0x51,
	0x1c, 0x4d, 0xc7, 0xe2, 0x3b, 0xc2, 0xac, 0x46, 0xf4, 0x03, 0xb8, 0x58, 0x5b, 0xa7, 0x4f, 0xb1,
	0xcf, 0xc6, 0x53, 0x40, 0x7f, 0xb4, 0x60, 0xcd, 0x65, 0x3e, 0x0b, 0x13, 0xfe, 0x57, 0xdf, 0x6e,
	0x46, 0x3b, 0x67, 0x57, 0xdb, 0xb9, 0x32, 0xcd, 0x6d, 0x83, 0xe6, 0xa2, 0x09, 0xea, 0x94, 0x9b,
	0x20, 0x7a, 0x1f, 0xd6, 0x8c, 0x5d, 0xe3, 0xbb, 0xe6, 0x79, 0xe8, 0xa5, 0xea, 0x35, 0x84, 0x27,
	0xe3, 0xb2, 0x3a, 0x19, 0x75, 0xbb, 0x70, 0x73, 0x2c, 0x7d, 0x4d, 0x6c, 0xf3, 0xb1, 0x36, 0x39,
	0x9a, 0x3c, 0x8a, 0x17, 0xdf, 0x26, 0xfd, 0xc9, 0x86, 0xcb, 0x2e, 0x4b, 0xf4, 0xf3, 0x85, 0x25,
	0x58, 0x7a, 0x2a, 0x36, 0x62, 0x69, 0xdd, 0xdc, 0x7f, 0xf7, 0x69, 0x5b, 0xd4, 0xea, 0x25, 0xed,
	0x4a, 0xab, 0xe1, 0xb4, 0xdf, 0x98, 0x3a, 0xe5, 0x07, 0x21, 0x54, 0x1f, 0x84, 0xc3, 0x42, 0xee,
	0x81, 0x94, 0x3b, 0x6f, 0x0b, 0x2a, 0xcf, 0x8a, 0x42, 0xeb, 0x7d, 0xb8, 0x58, 0xa7, 0x75, 0x26,
	0x48, 0x34, 0x22, 0xc8, 0xaf, 0xc5, 0x8a, 0x9d, 0xbe, 0x07, 0x1b, 0xc7, 0xa8, 0x9d, 0x91, 0x97,
	0xa0, 0x13, 0x8a, 0x1f, 0x2a, 0x0b, 0xe9, 0x3c, 0x0b, 0x1b, 0xd7, 0xb8, 0xb8, 0x80, 0xde, 0x05,
	0xc7, 0x0c, 0x6f, 0x6f, 0xa6, 0xda, 0xf2, 0xa6, 0x24, 0x5a, 0xc7, 0x86, 0x6a, 0x74, 0x4b, 0x95,
	0x29, 0x35, 0xa2, 0x1f, 0xc2, 0x7a, 0xd5, 0x97, 0x94, 0x8d, 0x40, 0xdb, 0x2b, 0xae, 0x44, 0xf9,
	0xbb, 0xe4, 0xbd, 0xd5, 0xe0, 0xdd, 0xd6, 0xbc, 0x3f, 0x05, 0xab, 0xe6, 0x7e, 0x46, 0xb7, 0x32,
	0x72, 0x1e, 0xec, 0xd1, 0xad, 0x9c, 0x39, 0xf1, 0x93, 0x7e, 0x6f, 0x09, 0xb6, 0x1e, 0xd7, 0x1c,
	0x58, 0x15, 0xcd, 0xe2, 0xd5, 0x24, 0x8f, 0xbb, 0x55, 0x1b, 0xb7, 0xad, 0xc5, 0x7d, 0x4c, 0x5d,
	0xa1, 0x5f, 0xc1, 0x66, 0x53, 0x44, 0x8a, 0xeb, 0xc5, 0x63, 0x6a, 0xe2, 0xad, 0xfc, 0x7d, 0xdb,
	0xf8, 0xfe, 0x7d, 0xf8, 0x9f, 0xc9, 0x5d, 0x5e, 0xc2, 0x86, 0x66, 0x09, 0x5b, 0x20, 0xa7, 0x3f,
	0xae, 0x0a, 0xad, 0x9e, 0x5b, 0x4f, 0xe6, 0x2e, 0xbd, 0x2b, 0xfc, 0xd7, 0x85, 0x4b, 0xae, 0x41,
	0x17, 0x51, 0xea, 0x09, 0xd5, 0x1c, 0xac, 0xc2, 0xd1, 0xef, 0x5a, 0x55, 0x67, 0xaa, 0xab, 0xf9,
	0xb7, 0x76, 0xe0, 0xa5, 0x22, 0xd8, 0xd5, 0x8b, 0xa0, 0xd1, 0x9b, 0xf7, 0xaa, 0xbd, 0xf9, 0xb3,
	0xa2, 0x1c, 0xe9, 0x6c, 0xe0, 0x83, 0x76, 0xde, 0x06, 0x20, 0x0d, 0x38, 0xa0, 0x2f, 0x56, 0xaf,
	0x99, 0x87, 0x19, 0x4b, 0x6b, 0x22, 0xb1, 0xf4, 0xab, 0xfc, 0x57, 0x0b, 0x2e, 0x99, 0x2b, 0x45,
	0x47, 0xaf, 0xd2, 0x7d, 0x03, 0xfa, 0xa8, 0xcf, 0x1b, 0xd3, 0xb1, 0x5a, 0x5a, 0x18, 0x04, 0xed,
	0x72, 0xc3, 0xfb, 0xa5, 0x72, 0xac, 0x68, 0x37, 0xed, 0x73, 0xac, 0x70, 0x9e, 0x63, 0xed, 0x12,
	0xb6, 0x64, 0x27, 0x57, 0x61, 0xc5, 0x97, 0xd2, 0xe7, 0x40, 0xe4, 0x5e, 0x37, 0xd2, 0x2f, 0xe1,
	0x4a, 0x5d, 0xe4, 0xc5, 0xae, 0x4b, 0x9f, 0xe4, 0x7a, 0x17, 0x5b, 0xb1, 0x93, 0x6b, 0xb0, 0x3a,
	0x0f, 0x23, 0x9c, 0x1c, 0xea, 0xbb, 0xa9, 0x9b, 0x3a, 0xe8, 0xca, 0xff, 0x63, 0xdf, 0xf8, 0x33,
	0x00, 0x00, 0xff, 0xff, 0x67, 0x8d, 0xd0, 0xce, 0xde, 0x16, 0x00, 0x00,
}
