// Code generated by protoc-gen-go. DO NOT EDIT.
// source: issuance.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 发行信息
type Issuance struct {
	IssuanceId             string        `protobuf:"bytes,1,opt,name=issuanceId,proto3" json:"issuanceId,omitempty"`
	TotalBalance           int64         `protobuf:"varint,2,opt,name=totalBalance,proto3" json:"totalBalance,omitempty"`
	DebtCeiling            int64         `protobuf:"varint,3,opt,name=debtCeiling,proto3" json:"debtCeiling,omitempty"`
	LiquidationRatio       int64         `protobuf:"varint,4,opt,name=liquidationRatio,proto3" json:"liquidationRatio,omitempty"`
	CollateralValue        int64         `protobuf:"varint,5,opt,name=collateralValue,proto3" json:"collateralValue,omitempty"`
	DebtValue              int64         `protobuf:"varint,6,opt,name=debtValue,proto3" json:"debtValue,omitempty"`
	DebtRecords            []*DebtRecord `protobuf:"bytes,7,rep,name=debtRecords,proto3" json:"debtRecords,omitempty"`
	InvalidRecords         []*DebtRecord `protobuf:"bytes,8,rep,name=invalidRecords,proto3" json:"invalidRecords,omitempty"`
	Status                 int32         `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	LatestLiquidationPrice int64         `protobuf:"varint,10,opt,name=latestLiquidationPrice,proto3" json:"latestLiquidationPrice,omitempty"`
	Period                 int64         `protobuf:"varint,11,opt,name=period,proto3" json:"period,omitempty"`
	LatestExpireTime       int64         `protobuf:"varint,12,opt,name=latestExpireTime,proto3" json:"latestExpireTime,omitempty"`
	CreateTime             int64         `protobuf:"varint,13,opt,name=createTime,proto3" json:"createTime,omitempty"`
	Balance                int64         `protobuf:"varint,14,opt,name=balance,proto3" json:"balance,omitempty"`
	IssuerAddr             string        `protobuf:"bytes,15,opt,name=issuerAddr,proto3" json:"issuerAddr,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}      `json:"-"`
	XXX_unrecognized       []byte        `json:"-"`
	XXX_sizecache          int32         `json:"-"`
}

func (m *Issuance) Reset()         { *m = Issuance{} }
func (m *Issuance) String() string { return proto.CompactTextString(m) }
func (*Issuance) ProtoMessage()    {}
func (*Issuance) Descriptor() ([]byte, []int) {
	return fileDescriptor_7110f4228953d675, []int{0}
}

func (m *Issuance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Issuance.Unmarshal(m, b)
}
func (m *Issuance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Issuance.Marshal(b, m, deterministic)
}
func (m *Issuance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Issuance.Merge(m, src)
}
func (m *Issuance) XXX_Size() int {
	return xxx_messageInfo_Issuance.Size(m)
}
func (m *Issuance) XXX_DiscardUnknown() {
	xxx_messageInfo_Issuance.DiscardUnknown(m)
}

var xxx_messageInfo_Issuance proto.InternalMessageInfo

func (m *Issuance) GetIssuanceId() string {
	if m != nil {
		return m.IssuanceId
	}
	return ""
}

func (m *Issuance) GetTotalBalance() int64 {
	if m != nil {
		return m.TotalBalance
	}
	return 0
}

func (m *Issuance) GetDebtCeiling() int64 {
	if m != nil {
		return m.DebtCeiling
	}
	return 0
}

func (m *Issuance) GetLiquidationRatio() int64 {
	if m != nil {
		return m.LiquidationRatio
	}
	return 0
}

func (m *Issuance) GetCollateralValue() int64 {
	if m != nil {
		return m.CollateralValue
	}
	return 0
}

func (m *Issuance) GetDebtValue() int64 {
	if m != nil {
		return m.DebtValue
	}
	return 0
}

func (m *Issuance) GetDebtRecords() []*DebtRecord {
	if m != nil {
		return m.DebtRecords
	}
	return nil
}

func (m *Issuance) GetInvalidRecords() []*DebtRecord {
	if m != nil {
		return m.InvalidRecords
	}
	return nil
}

func (m *Issuance) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Issuance) GetLatestLiquidationPrice() int64 {
	if m != nil {
		return m.LatestLiquidationPrice
	}
	return 0
}

func (m *Issuance) GetPeriod() int64 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *Issuance) GetLatestExpireTime() int64 {
	if m != nil {
		return m.LatestExpireTime
	}
	return 0
}

func (m *Issuance) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Issuance) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Issuance) GetIssuerAddr() string {
	if m != nil {
		return m.IssuerAddr
	}
	return ""
}

// 抵押记录
type DebtRecord struct {
	AccountAddr          string   `protobuf:"bytes,1,opt,name=accountAddr,proto3" json:"accountAddr,omitempty"`
	StartTime            int64    `protobuf:"varint,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
	CollateralValue      int64    `protobuf:"varint,3,opt,name=collateralValue,proto3" json:"collateralValue,omitempty"`
	CollateralPrice      int64    `protobuf:"varint,4,opt,name=collateralPrice,proto3" json:"collateralPrice,omitempty"`
	DebtValue            int64    `protobuf:"varint,5,opt,name=debtValue,proto3" json:"debtValue,omitempty"`
	LiquidationPrice     int64    `protobuf:"varint,6,opt,name=liquidationPrice,proto3" json:"liquidationPrice,omitempty"`
	Status               int32    `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	LiquidateTime        int64    `protobuf:"varint,8,opt,name=liquidateTime,proto3" json:"liquidateTime,omitempty"`
	ExpireTime           int64    `protobuf:"varint,9,opt,name=expireTime,proto3" json:"expireTime,omitempty"`
	PreStatus            int32    `protobuf:"varint,10,opt,name=preStatus,proto3" json:"preStatus,omitempty"`
	DebtId               string   `protobuf:"bytes,11,opt,name=debtId,proto3" json:"debtId,omitempty"`
	IssuId               string   `protobuf:"bytes,12,opt,name=issuId,proto3" json:"issuId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DebtRecord) Reset()         { *m = DebtRecord{} }
func (m *DebtRecord) String() string { return proto.CompactTextString(m) }
func (*DebtRecord) ProtoMessage()    {}
func (*DebtRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_7110f4228953d675, []int{1}
}

func (m *DebtRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebtRecord.Unmarshal(m, b)
}
func (m *DebtRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebtRecord.Marshal(b, m, deterministic)
}
func (m *DebtRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebtRecord.Merge(m, src)
}
func (m *DebtRecord) XXX_Size() int {
	return xxx_messageInfo_DebtRecord.Size(m)
}
func (m *DebtRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_DebtRecord.DiscardUnknown(m)
}

var xxx_messageInfo_DebtRecord proto.InternalMessageInfo

func (m *DebtRecord) GetAccountAddr() string {
	if m != nil {
		return m.AccountAddr
	}
	return ""
}

func (m *DebtRecord) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *DebtRecord) GetCollateralValue() int64 {
	if m != nil {
		return m.CollateralValue
	}
	return 0
}

func (m *DebtRecord) GetCollateralPrice() int64 {
	if m != nil {
		return m.CollateralPrice
	}
	return 0
}

func (m *DebtRecord) GetDebtValue() int64 {
	if m != nil {
		return m.DebtValue
	}
	return 0
}

func (m *DebtRecord) GetLiquidationPrice() int64 {
	if m != nil {
		return m.LiquidationPrice
	}
	return 0
}

func (m *DebtRecord) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DebtRecord) GetLiquidateTime() int64 {
	if m != nil {
		return m.LiquidateTime
	}
	return 0
}

func (m *DebtRecord) GetExpireTime() int64 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

func (m *DebtRecord) GetPreStatus() int32 {
	if m != nil {
		return m.PreStatus
	}
	return 0
}

func (m *DebtRecord) GetDebtId() string {
	if m != nil {
		return m.DebtId
	}
	return ""
}

func (m *DebtRecord) GetIssuId() string {
	if m != nil {
		return m.IssuId
	}
	return ""
}

// 资产价格记录
type IssuanceAssetPriceRecord struct {
	RecordTime           int64    `protobuf:"varint,1,opt,name=recordTime,proto3" json:"recordTime,omitempty"`
	BtyPrice             int64    `protobuf:"varint,2,opt,name=btyPrice,proto3" json:"btyPrice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssuanceAssetPriceRecord) Reset()         { *m = IssuanceAssetPriceRecord{} }
func (m *IssuanceAssetPriceRecord) String() string { return proto.CompactTextString(m) }
func (*IssuanceAssetPriceRecord) ProtoMessage()    {}
func (*IssuanceAssetPriceRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_7110f4228953d675, []int{2}
}

func (m *IssuanceAssetPriceRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssuanceAssetPriceRecord.Unmarshal(m, b)
}
func (m *IssuanceAssetPriceRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssuanceAssetPriceRecord.Marshal(b, m, deterministic)
}
func (m *IssuanceAssetPriceRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssuanceAssetPriceRecord.Merge(m, src)
}
func (m *IssuanceAssetPriceRecord) XXX_Size() int {
	return xxx_messageInfo_IssuanceAssetPriceRecord.Size(m)
}
func (m *IssuanceAssetPriceRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_IssuanceAssetPriceRecord.DiscardUnknown(m)
}

var xxx_messageInfo_IssuanceAssetPriceRecord proto.InternalMessageInfo

func (m *IssuanceAssetPriceRecord) GetRecordTime() int64 {
	if m != nil {
		return m.RecordTime
	}
	return 0
}

func (m *IssuanceAssetPriceRecord) GetBtyPrice() int64 {
	if m != nil {
		return m.BtyPrice
	}
	return 0
}

// action
type IssuanceAction struct {
	// Types that are valid to be assigned to Value:
	//	*IssuanceAction_Create
	//	*IssuanceAction_Debt
	//	*IssuanceAction_Repay
	//	*IssuanceAction_Feed
	//	*IssuanceAction_Close
	//	*IssuanceAction_Manage
	//	*IssuanceAction_Issuer
	Value                isIssuanceAction_Value `protobuf_oneof:"value"`
	Ty                   int32                  `protobuf:"varint,10,opt,name=ty,proto3" json:"ty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *IssuanceAction) Reset()         { *m = IssuanceAction{} }
func (m *IssuanceAction) String() string { return proto.CompactTextString(m) }
func (*IssuanceAction) ProtoMessage()    {}
func (*IssuanceAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_7110f4228953d675, []int{3}
}

func (m *IssuanceAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssuanceAction.Unmarshal(m, b)
}
func (m *IssuanceAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssuanceAction.Marshal(b, m, deterministic)
}
func (m *IssuanceAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssuanceAction.Merge(m, src)
}
func (m *IssuanceAction) XXX_Size() int {
	return xxx_messageInfo_IssuanceAction.Size(m)
}
func (m *IssuanceAction) XXX_DiscardUnknown() {
	xxx_messageInfo_IssuanceAction.DiscardUnknown(m)
}

var xxx_messageInfo_IssuanceAction proto.InternalMessageInfo

type isIssuanceAction_Value interface {
	isIssuanceAction_Value()
}

type IssuanceAction_Create struct {
	Create *IssuanceCreate `protobuf:"bytes,1,opt,name=create,proto3,oneof"`
}

type IssuanceAction_Debt struct {
	Debt *IssuanceDebt `protobuf:"bytes,2,opt,name=debt,proto3,oneof"`
}

type IssuanceAction_Repay struct {
	Repay *IssuanceRepay `protobuf:"bytes,3,opt,name=repay,proto3,oneof"`
}

type IssuanceAction_Feed struct {
	Feed *IssuanceFeed `protobuf:"bytes,4,opt,name=feed,proto3,oneof"`
}

type IssuanceAction_Close struct {
	Close *IssuanceClose `protobuf:"bytes,5,opt,name=close,proto3,oneof"`
}

type IssuanceAction_Manage struct {
	Manage *IssuanceManage `protobuf:"bytes,6,opt,name=manage,proto3,oneof"`
}

type IssuanceAction_Issuer struct {
	Issuer *IssuanceIssuer `protobuf:"bytes,7,opt,name=issuer,proto3,oneof"`
}

func (*IssuanceAction_Create) isIssuanceAction_Value() {}

func (*IssuanceAction_Debt) isIssuanceAction_Value() {}

func (*IssuanceAction_Repay) isIssuanceAction_Value() {}

func (*IssuanceAction_Feed) isIssuanceAction_Value() {}

func (*IssuanceAction_Close) isIssuanceAction_Value() {}

func (*IssuanceAction_Manage) isIssuanceAction_Value() {}

func (*IssuanceAction_Issuer) isIssuanceAction_Value() {}

func (m *IssuanceAction) GetValue() isIssuanceAction_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *IssuanceAction) GetCreate() *IssuanceCreate {
	if x, ok := m.GetValue().(*IssuanceAction_Create); ok {
		return x.Create
	}
	return nil
}

func (m *IssuanceAction) GetDebt() *IssuanceDebt {
	if x, ok := m.GetValue().(*IssuanceAction_Debt); ok {
		return x.Debt
	}
	return nil
}

func (m *IssuanceAction) GetRepay() *IssuanceRepay {
	if x, ok := m.GetValue().(*IssuanceAction_Repay); ok {
		return x.Repay
	}
	return nil
}

func (m *IssuanceAction) GetFeed() *IssuanceFeed {
	if x, ok := m.GetValue().(*IssuanceAction_Feed); ok {
		return x.Feed
	}
	return nil
}

func (m *IssuanceAction) GetClose() *IssuanceClose {
	if x, ok := m.GetValue().(*IssuanceAction_Close); ok {
		return x.Close
	}
	return nil
}

func (m *IssuanceAction) GetManage() *IssuanceManage {
	if x, ok := m.GetValue().(*IssuanceAction_Manage); ok {
		return x.Manage
	}
	return nil
}

func (m *IssuanceAction) GetIssuer() *IssuanceIssuer {
	if x, ok := m.GetValue().(*IssuanceAction_Issuer); ok {
		return x.Issuer
	}
	return nil
}

func (m *IssuanceAction) GetTy() int32 {
	if m != nil {
		return m.Ty
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*IssuanceAction) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*IssuanceAction_Create)(nil),
		(*IssuanceAction_Debt)(nil),
		(*IssuanceAction_Repay)(nil),
		(*IssuanceAction_Feed)(nil),
		(*IssuanceAction_Close)(nil),
		(*IssuanceAction_Manage)(nil),
		(*IssuanceAction_Issuer)(nil),
	}
}

type IssuanceManage struct {
	SuperAddrs           []string `protobuf:"bytes,1,rep,name=superAddrs,proto3" json:"superAddrs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssuanceManage) Reset()         { *m = IssuanceManage{} }
func (m *IssuanceManage) String() string { return proto.CompactTextString(m) }
func (*IssuanceManage) ProtoMessage()    {}
func (*IssuanceManage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7110f4228953d675, []int{4}
}

func (m *IssuanceManage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssuanceManage.Unmarshal(m, b)
}
func (m *IssuanceManage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssuanceManage.Marshal(b, m, deterministic)
}
func (m *IssuanceManage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssuanceManage.Merge(m, src)
}
func (m *IssuanceManage) XXX_Size() int {
	return xxx_messageInfo_IssuanceManage.Size(m)
}
func (m *IssuanceManage) XXX_DiscardUnknown() {
	xxx_messageInfo_IssuanceManage.DiscardUnknown(m)
}

var xxx_messageInfo_IssuanceManage proto.InternalMessageInfo

func (m *IssuanceManage) GetSuperAddrs() []string {
	if m != nil {
		return m.SuperAddrs
	}
	return nil
}

type IssuanceIssuer struct {
	IssuerAddr           string   `protobuf:"bytes,1,opt,name=issuerAddr,proto3" json:"issuerAddr,omitempty"`
	Op                   string   `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssuanceIssuer) Reset()         { *m = IssuanceIssuer{} }
func (m *IssuanceIssuer) String() string { return proto.CompactTextString(m) }
func (*IssuanceIssuer) ProtoMessage()    {}
func (*IssuanceIssuer) Descriptor() ([]byte, []int) {
	return fileDescriptor_7110f4228953d675, []int{5}
}

func (m *IssuanceIssuer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssuanceIssuer.Unmarshal(m, b)
}
func (m *IssuanceIssuer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssuanceIssuer.Marshal(b, m, deterministic)
}
func (m *IssuanceIssuer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssuanceIssuer.Merge(m, src)
}
func (m *IssuanceIssuer) XXX_Size() int {
	return xxx_messageInfo_IssuanceIssuer.Size(m)
}
func (m *IssuanceIssuer) XXX_DiscardUnknown() {
	xxx_messageInfo_IssuanceIssuer.DiscardUnknown(m)
}

var xxx_messageInfo_IssuanceIssuer proto.InternalMessageInfo

func (m *IssuanceIssuer) GetIssuerAddr() string {
	if m != nil {
		return m.IssuerAddr
	}
	return ""
}

func (m *IssuanceIssuer) GetOp() string {
	if m != nil {
		return m.Op
	}
	return ""
}

// 创建发行
type IssuanceCreate struct {
	TotalBalance         int64    `protobuf:"varint,1,opt,name=totalBalance,proto3" json:"totalBalance,omitempty"`
	DebtCeiling          int64    `protobuf:"varint,2,opt,name=debtCeiling,proto3" json:"debtCeiling,omitempty"`
	LiquidationRatio     int64    `protobuf:"varint,3,opt,name=liquidationRatio,proto3" json:"liquidationRatio,omitempty"`
	Period               int64    `protobuf:"varint,4,opt,name=period,proto3" json:"period,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssuanceCreate) Reset()         { *m = IssuanceCreate{} }
func (m *IssuanceCreate) String() string { return proto.CompactTextString(m) }
func (*IssuanceCreate) ProtoMessage()    {}
func (*IssuanceCreate) Descriptor() ([]byte, []int) {
	return fileDescriptor_7110f4228953d675, []int{6}
}

func (m *IssuanceCreate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssuanceCreate.Unmarshal(m, b)
}
func (m *IssuanceCreate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssuanceCreate.Marshal(b, m, deterministic)
}
func (m *IssuanceCreate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssuanceCreate.Merge(m, src)
}
func (m *IssuanceCreate) XXX_Size() int {
	return xxx_messageInfo_IssuanceCreate.Size(m)
}
func (m *IssuanceCreate) XXX_DiscardUnknown() {
	xxx_messageInfo_IssuanceCreate.DiscardUnknown(m)
}

var xxx_messageInfo_IssuanceCreate proto.InternalMessageInfo

func (m *IssuanceCreate) GetTotalBalance() int64 {
	if m != nil {
		return m.TotalBalance
	}
	return 0
}

func (m *IssuanceCreate) GetDebtCeiling() int64 {
	if m != nil {
		return m.DebtCeiling
	}
	return 0
}

func (m *IssuanceCreate) GetLiquidationRatio() int64 {
	if m != nil {
		return m.LiquidationRatio
	}
	return 0
}

func (m *IssuanceCreate) GetPeriod() int64 {
	if m != nil {
		return m.Period
	}
	return 0
}

// 抵押
type IssuanceDebt struct {
	IssuanceId           string   `protobuf:"bytes,1,opt,name=issuanceId,proto3" json:"issuanceId,omitempty"`
	Value                int64    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssuanceDebt) Reset()         { *m = IssuanceDebt{} }
func (m *IssuanceDebt) String() string { return proto.CompactTextString(m) }
func (*IssuanceDebt) ProtoMessage()    {}
func (*IssuanceDebt) Descriptor() ([]byte, []int) {
	return fileDescriptor_7110f4228953d675, []int{7}
}

func (m *IssuanceDebt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssuanceDebt.Unmarshal(m, b)
}
func (m *IssuanceDebt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssuanceDebt.Marshal(b, m, deterministic)
}
func (m *IssuanceDebt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssuanceDebt.Merge(m, src)
}
func (m *IssuanceDebt) XXX_Size() int {
	return xxx_messageInfo_IssuanceDebt.Size(m)
}
func (m *IssuanceDebt) XXX_DiscardUnknown() {
	xxx_messageInfo_IssuanceDebt.DiscardUnknown(m)
}

var xxx_messageInfo_IssuanceDebt proto.InternalMessageInfo

func (m *IssuanceDebt) GetIssuanceId() string {
	if m != nil {
		return m.IssuanceId
	}
	return ""
}

func (m *IssuanceDebt) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

// 质押清算
type IssuanceRepay struct {
	IssuanceId           string   `protobuf:"bytes,1,opt,name=issuanceId,proto3" json:"issuanceId,omitempty"`
	DebtId               string   `protobuf:"bytes,2,opt,name=debtId,proto3" json:"debtId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssuanceRepay) Reset()         { *m = IssuanceRepay{} }
func (m *IssuanceRepay) String() string { return proto.CompactTextString(m) }
func (*IssuanceRepay) ProtoMessage()    {}
func (*IssuanceRepay) Descriptor() ([]byte, []int) {
	return fileDescriptor_7110f4228953d675, []int{8}
}

func (m *IssuanceRepay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssuanceRepay.Unmarshal(m, b)
}
func (m *IssuanceRepay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssuanceRepay.Marshal(b, m, deterministic)
}
func (m *IssuanceRepay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssuanceRepay.Merge(m, src)
}
func (m *IssuanceRepay) XXX_Size() int {
	return xxx_messageInfo_IssuanceRepay.Size(m)
}
func (m *IssuanceRepay) XXX_DiscardUnknown() {
	xxx_messageInfo_IssuanceRepay.DiscardUnknown(m)
}

var xxx_messageInfo_IssuanceRepay proto.InternalMessageInfo

func (m *IssuanceRepay) GetIssuanceId() string {
	if m != nil {
		return m.IssuanceId
	}
	return ""
}

func (m *IssuanceRepay) GetDebtId() string {
	if m != nil {
		return m.DebtId
	}
	return ""
}

// 喂价
type IssuanceFeed struct {
	CollType             int32    `protobuf:"varint,1,opt,name=collType,proto3" json:"collType,omitempty"`
	Price                []int64  `protobuf:"varint,2,rep,packed,name=price,proto3" json:"price,omitempty"`
	Volume               []int64  `protobuf:"varint,3,rep,packed,name=volume,proto3" json:"volume,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssuanceFeed) Reset()         { *m = IssuanceFeed{} }
func (m *IssuanceFeed) String() string { return proto.CompactTextString(m) }
func (*IssuanceFeed) ProtoMessage()    {}
func (*IssuanceFeed) Descriptor() ([]byte, []int) {
	return fileDescriptor_7110f4228953d675, []int{9}
}

func (m *IssuanceFeed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssuanceFeed.Unmarshal(m, b)
}
func (m *IssuanceFeed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssuanceFeed.Marshal(b, m, deterministic)
}
func (m *IssuanceFeed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssuanceFeed.Merge(m, src)
}
func (m *IssuanceFeed) XXX_Size() int {
	return xxx_messageInfo_IssuanceFeed.Size(m)
}
func (m *IssuanceFeed) XXX_DiscardUnknown() {
	xxx_messageInfo_IssuanceFeed.DiscardUnknown(m)
}

var xxx_messageInfo_IssuanceFeed proto.InternalMessageInfo

func (m *IssuanceFeed) GetCollType() int32 {
	if m != nil {
		return m.CollType
	}
	return 0
}

func (m *IssuanceFeed) GetPrice() []int64 {
	if m != nil {
		return m.Price
	}
	return nil
}

func (m *IssuanceFeed) GetVolume() []int64 {
	if m != nil {
		return m.Volume
	}
	return nil
}

// 借贷关闭
type IssuanceClose struct {
	IssuanceId           string   `protobuf:"bytes,1,opt,name=issuanceId,proto3" json:"issuanceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssuanceClose) Reset()         { *m = IssuanceClose{} }
func (m *IssuanceClose) String() string { return proto.CompactTextString(m) }
func (*IssuanceClose) ProtoMessage()    {}
func (*IssuanceClose) Descriptor() ([]byte, []int) {
	return fileDescriptor_7110f4228953d675, []int{10}
}

func (m *IssuanceClose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssuanceClose.Unmarshal(m, b)
}
func (m *IssuanceClose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssuanceClose.Marshal(b, m, deterministic)
}
func (m *IssuanceClose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssuanceClose.Merge(m, src)
}
func (m *IssuanceClose) XXX_Size() int {
	return xxx_messageInfo_IssuanceClose.Size(m)
}
func (m *IssuanceClose) XXX_DiscardUnknown() {
	xxx_messageInfo_IssuanceClose.DiscardUnknown(m)
}

var xxx_messageInfo_IssuanceClose proto.InternalMessageInfo

func (m *IssuanceClose) GetIssuanceId() string {
	if m != nil {
		return m.IssuanceId
	}
	return ""
}

// exec_local 发行信息
type ReceiptIssuance struct {
	IssuanceId           string   `protobuf:"bytes,1,opt,name=issuanceId,proto3" json:"issuanceId,omitempty"`
	AccountAddr          string   `protobuf:"bytes,2,opt,name=accountAddr,proto3" json:"accountAddr,omitempty"`
	DebtId               string   `protobuf:"bytes,3,opt,name=debtId,proto3" json:"debtId,omitempty"`
	Status               int32    `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiptIssuance) Reset()         { *m = ReceiptIssuance{} }
func (m *ReceiptIssuance) String() string { return proto.CompactTextString(m) }
func (*ReceiptIssuance) ProtoMessage()    {}
func (*ReceiptIssuance) Descriptor() ([]byte, []int) {
	return fileDescriptor_7110f4228953d675, []int{11}
}

func (m *ReceiptIssuance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptIssuance.Unmarshal(m, b)
}
func (m *ReceiptIssuance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptIssuance.Marshal(b, m, deterministic)
}
func (m *ReceiptIssuance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptIssuance.Merge(m, src)
}
func (m *ReceiptIssuance) XXX_Size() int {
	return xxx_messageInfo_ReceiptIssuance.Size(m)
}
func (m *ReceiptIssuance) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptIssuance.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptIssuance proto.InternalMessageInfo

func (m *ReceiptIssuance) GetIssuanceId() string {
	if m != nil {
		return m.IssuanceId
	}
	return ""
}

func (m *ReceiptIssuance) GetAccountAddr() string {
	if m != nil {
		return m.AccountAddr
	}
	return ""
}

func (m *ReceiptIssuance) GetDebtId() string {
	if m != nil {
		return m.DebtId
	}
	return ""
}

func (m *ReceiptIssuance) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// exec_local issuid记录信息
type ReceiptIssuanceID struct {
	IssuanceId           string   `protobuf:"bytes,1,opt,name=issuanceId,proto3" json:"issuanceId,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiptIssuanceID) Reset()         { *m = ReceiptIssuanceID{} }
func (m *ReceiptIssuanceID) String() string { return proto.CompactTextString(m) }
func (*ReceiptIssuanceID) ProtoMessage()    {}
func (*ReceiptIssuanceID) Descriptor() ([]byte, []int) {
	return fileDescriptor_7110f4228953d675, []int{12}
}

func (m *ReceiptIssuanceID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptIssuanceID.Unmarshal(m, b)
}
func (m *ReceiptIssuanceID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptIssuanceID.Marshal(b, m, deterministic)
}
func (m *ReceiptIssuanceID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptIssuanceID.Merge(m, src)
}
func (m *ReceiptIssuanceID) XXX_Size() int {
	return xxx_messageInfo_ReceiptIssuanceID.Size(m)
}
func (m *ReceiptIssuanceID) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptIssuanceID.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptIssuanceID proto.InternalMessageInfo

func (m *ReceiptIssuanceID) GetIssuanceId() string {
	if m != nil {
		return m.IssuanceId
	}
	return ""
}

func (m *ReceiptIssuanceID) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// exec_local 抵押记录信息列表
type IssuanceRecords struct {
	Records              []*ReceiptIssuance `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *IssuanceRecords) Reset()         { *m = IssuanceRecords{} }
func (m *IssuanceRecords) String() string { return proto.CompactTextString(m) }
func (*IssuanceRecords) ProtoMessage()    {}
func (*IssuanceRecords) Descriptor() ([]byte, []int) {
	return fileDescriptor_7110f4228953d675, []int{13}
}

func (m *IssuanceRecords) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssuanceRecords.Unmarshal(m, b)
}
func (m *IssuanceRecords) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssuanceRecords.Marshal(b, m, deterministic)
}
func (m *IssuanceRecords) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssuanceRecords.Merge(m, src)
}
func (m *IssuanceRecords) XXX_Size() int {
	return xxx_messageInfo_IssuanceRecords.Size(m)
}
func (m *IssuanceRecords) XXX_DiscardUnknown() {
	xxx_messageInfo_IssuanceRecords.DiscardUnknown(m)
}

var xxx_messageInfo_IssuanceRecords proto.InternalMessageInfo

func (m *IssuanceRecords) GetRecords() []*ReceiptIssuance {
	if m != nil {
		return m.Records
	}
	return nil
}

// 根据ID查询发行信息
type ReqIssuanceInfo struct {
	IssuanceId           string   `protobuf:"bytes,1,opt,name=issuanceId,proto3" json:"issuanceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqIssuanceInfo) Reset()         { *m = ReqIssuanceInfo{} }
func (m *ReqIssuanceInfo) String() string { return proto.CompactTextString(m) }
func (*ReqIssuanceInfo) ProtoMessage()    {}
func (*ReqIssuanceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7110f4228953d675, []int{14}
}

func (m *ReqIssuanceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqIssuanceInfo.Unmarshal(m, b)
}
func (m *ReqIssuanceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqIssuanceInfo.Marshal(b, m, deterministic)
}
func (m *ReqIssuanceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqIssuanceInfo.Merge(m, src)
}
func (m *ReqIssuanceInfo) XXX_Size() int {
	return xxx_messageInfo_ReqIssuanceInfo.Size(m)
}
func (m *ReqIssuanceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqIssuanceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReqIssuanceInfo proto.InternalMessageInfo

func (m *ReqIssuanceInfo) GetIssuanceId() string {
	if m != nil {
		return m.IssuanceId
	}
	return ""
}

// 返回一期发行信息
type RepIssuanceCurrentInfo struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	TotalBalance         int64    `protobuf:"varint,2,opt,name=totalBalance,proto3" json:"totalBalance,omitempty"`
	DebtCeiling          int64    `protobuf:"varint,3,opt,name=debtCeiling,proto3" json:"debtCeiling,omitempty"`
	LiquidationRatio     int64    `protobuf:"varint,4,opt,name=liquidationRatio,proto3" json:"liquidationRatio,omitempty"`
	Balance              int64    `protobuf:"varint,5,opt,name=balance,proto3" json:"balance,omitempty"`
	CollateralValue      int64    `protobuf:"varint,6,opt,name=collateralValue,proto3" json:"collateralValue,omitempty"`
	DebtValue            int64    `protobuf:"varint,7,opt,name=debtValue,proto3" json:"debtValue,omitempty"`
	Period               int64    `protobuf:"varint,8,opt,name=period,proto3" json:"period,omitempty"`
	IssuId               string   `protobuf:"bytes,9,opt,name=issuId,proto3" json:"issuId,omitempty"`
	CreateTime           int64    `protobuf:"varint,10,opt,name=createTime,proto3" json:"createTime,omitempty"`
	RecordNum            int64    `protobuf:"varint,11,opt,name=recordNum,proto3" json:"recordNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepIssuanceCurrentInfo) Reset()         { *m = RepIssuanceCurrentInfo{} }
func (m *RepIssuanceCurrentInfo) String() string { return proto.CompactTextString(m) }
func (*RepIssuanceCurrentInfo) ProtoMessage()    {}
func (*RepIssuanceCurrentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7110f4228953d675, []int{15}
}

func (m *RepIssuanceCurrentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepIssuanceCurrentInfo.Unmarshal(m, b)
}
func (m *RepIssuanceCurrentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepIssuanceCurrentInfo.Marshal(b, m, deterministic)
}
func (m *RepIssuanceCurrentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepIssuanceCurrentInfo.Merge(m, src)
}
func (m *RepIssuanceCurrentInfo) XXX_Size() int {
	return xxx_messageInfo_RepIssuanceCurrentInfo.Size(m)
}
func (m *RepIssuanceCurrentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RepIssuanceCurrentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RepIssuanceCurrentInfo proto.InternalMessageInfo

func (m *RepIssuanceCurrentInfo) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *RepIssuanceCurrentInfo) GetTotalBalance() int64 {
	if m != nil {
		return m.TotalBalance
	}
	return 0
}

func (m *RepIssuanceCurrentInfo) GetDebtCeiling() int64 {
	if m != nil {
		return m.DebtCeiling
	}
	return 0
}

func (m *RepIssuanceCurrentInfo) GetLiquidationRatio() int64 {
	if m != nil {
		return m.LiquidationRatio
	}
	return 0
}

func (m *RepIssuanceCurrentInfo) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *RepIssuanceCurrentInfo) GetCollateralValue() int64 {
	if m != nil {
		return m.CollateralValue
	}
	return 0
}

func (m *RepIssuanceCurrentInfo) GetDebtValue() int64 {
	if m != nil {
		return m.DebtValue
	}
	return 0
}

func (m *RepIssuanceCurrentInfo) GetPeriod() int64 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *RepIssuanceCurrentInfo) GetIssuId() string {
	if m != nil {
		return m.IssuId
	}
	return ""
}

func (m *RepIssuanceCurrentInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *RepIssuanceCurrentInfo) GetRecordNum() int64 {
	if m != nil {
		return m.RecordNum
	}
	return 0
}

// 根据ID列表查询多期发行信息
type ReqIssuanceInfos struct {
	IssuanceIds          []string `protobuf:"bytes,1,rep,name=issuanceIds,proto3" json:"issuanceIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqIssuanceInfos) Reset()         { *m = ReqIssuanceInfos{} }
func (m *ReqIssuanceInfos) String() string { return proto.CompactTextString(m) }
func (*ReqIssuanceInfos) ProtoMessage()    {}
func (*ReqIssuanceInfos) Descriptor() ([]byte, []int) {
	return fileDescriptor_7110f4228953d675, []int{16}
}

func (m *ReqIssuanceInfos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqIssuanceInfos.Unmarshal(m, b)
}
func (m *ReqIssuanceInfos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqIssuanceInfos.Marshal(b, m, deterministic)
}
func (m *ReqIssuanceInfos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqIssuanceInfos.Merge(m, src)
}
func (m *ReqIssuanceInfos) XXX_Size() int {
	return xxx_messageInfo_ReqIssuanceInfos.Size(m)
}
func (m *ReqIssuanceInfos) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqIssuanceInfos.DiscardUnknown(m)
}

var xxx_messageInfo_ReqIssuanceInfos proto.InternalMessageInfo

func (m *ReqIssuanceInfos) GetIssuanceIds() []string {
	if m != nil {
		return m.IssuanceIds
	}
	return nil
}

// 返回多期发行信息
type RepIssuanceCurrentInfos struct {
	Infos                []*RepIssuanceCurrentInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *RepIssuanceCurrentInfos) Reset()         { *m = RepIssuanceCurrentInfos{} }
func (m *RepIssuanceCurrentInfos) String() string { return proto.CompactTextString(m) }
func (*RepIssuanceCurrentInfos) ProtoMessage()    {}
func (*RepIssuanceCurrentInfos) Descriptor() ([]byte, []int) {
	return fileDescriptor_7110f4228953d675, []int{17}
}

func (m *RepIssuanceCurrentInfos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepIssuanceCurrentInfos.Unmarshal(m, b)
}
func (m *RepIssuanceCurrentInfos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepIssuanceCurrentInfos.Marshal(b, m, deterministic)
}
func (m *RepIssuanceCurrentInfos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepIssuanceCurrentInfos.Merge(m, src)
}
func (m *RepIssuanceCurrentInfos) XXX_Size() int {
	return xxx_messageInfo_RepIssuanceCurrentInfos.Size(m)
}
func (m *RepIssuanceCurrentInfos) XXX_DiscardUnknown() {
	xxx_messageInfo_RepIssuanceCurrentInfos.DiscardUnknown(m)
}

var xxx_messageInfo_RepIssuanceCurrentInfos proto.InternalMessageInfo

func (m *RepIssuanceCurrentInfos) GetInfos() []*RepIssuanceCurrentInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

// 根据发行状态查询
type ReqIssuanceByStatus struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	IssuanceId           string   `protobuf:"bytes,2,opt,name=issuanceId,proto3" json:"issuanceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqIssuanceByStatus) Reset()         { *m = ReqIssuanceByStatus{} }
func (m *ReqIssuanceByStatus) String() string { return proto.CompactTextString(m) }
func (*ReqIssuanceByStatus) ProtoMessage()    {}
func (*ReqIssuanceByStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_7110f4228953d675, []int{18}
}

func (m *ReqIssuanceByStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqIssuanceByStatus.Unmarshal(m, b)
}
func (m *ReqIssuanceByStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqIssuanceByStatus.Marshal(b, m, deterministic)
}
func (m *ReqIssuanceByStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqIssuanceByStatus.Merge(m, src)
}
func (m *ReqIssuanceByStatus) XXX_Size() int {
	return xxx_messageInfo_ReqIssuanceByStatus.Size(m)
}
func (m *ReqIssuanceByStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqIssuanceByStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ReqIssuanceByStatus proto.InternalMessageInfo

func (m *ReqIssuanceByStatus) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ReqIssuanceByStatus) GetIssuanceId() string {
	if m != nil {
		return m.IssuanceId
	}
	return ""
}

// 返回发行ID列表
type RepIssuanceIDs struct {
	IDs                  []string `protobuf:"bytes,1,rep,name=IDs,proto3" json:"IDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepIssuanceIDs) Reset()         { *m = RepIssuanceIDs{} }
func (m *RepIssuanceIDs) String() string { return proto.CompactTextString(m) }
func (*RepIssuanceIDs) ProtoMessage()    {}
func (*RepIssuanceIDs) Descriptor() ([]byte, []int) {
	return fileDescriptor_7110f4228953d675, []int{19}
}

func (m *RepIssuanceIDs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepIssuanceIDs.Unmarshal(m, b)
}
func (m *RepIssuanceIDs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepIssuanceIDs.Marshal(b, m, deterministic)
}
func (m *RepIssuanceIDs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepIssuanceIDs.Merge(m, src)
}
func (m *RepIssuanceIDs) XXX_Size() int {
	return xxx_messageInfo_RepIssuanceIDs.Size(m)
}
func (m *RepIssuanceIDs) XXX_DiscardUnknown() {
	xxx_messageInfo_RepIssuanceIDs.DiscardUnknown(m)
}

var xxx_messageInfo_RepIssuanceIDs proto.InternalMessageInfo

func (m *RepIssuanceIDs) GetIDs() []string {
	if m != nil {
		return m.IDs
	}
	return nil
}

// 根据用户地址查询抵押记录
type ReqIssuanceRecords struct {
	IssuanceId           string   `protobuf:"bytes,1,opt,name=issuanceId,proto3" json:"issuanceId,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Status               int32    `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	DebtId               string   `protobuf:"bytes,4,opt,name=debtId,proto3" json:"debtId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqIssuanceRecords) Reset()         { *m = ReqIssuanceRecords{} }
func (m *ReqIssuanceRecords) String() string { return proto.CompactTextString(m) }
func (*ReqIssuanceRecords) ProtoMessage()    {}
func (*ReqIssuanceRecords) Descriptor() ([]byte, []int) {
	return fileDescriptor_7110f4228953d675, []int{20}
}

func (m *ReqIssuanceRecords) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqIssuanceRecords.Unmarshal(m, b)
}
func (m *ReqIssuanceRecords) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqIssuanceRecords.Marshal(b, m, deterministic)
}
func (m *ReqIssuanceRecords) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqIssuanceRecords.Merge(m, src)
}
func (m *ReqIssuanceRecords) XXX_Size() int {
	return xxx_messageInfo_ReqIssuanceRecords.Size(m)
}
func (m *ReqIssuanceRecords) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqIssuanceRecords.DiscardUnknown(m)
}

var xxx_messageInfo_ReqIssuanceRecords proto.InternalMessageInfo

func (m *ReqIssuanceRecords) GetIssuanceId() string {
	if m != nil {
		return m.IssuanceId
	}
	return ""
}

func (m *ReqIssuanceRecords) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *ReqIssuanceRecords) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ReqIssuanceRecords) GetDebtId() string {
	if m != nil {
		return m.DebtId
	}
	return ""
}

// 返回记录列表
type RepIssuanceRecords struct {
	Records              []*DebtRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RepIssuanceRecords) Reset()         { *m = RepIssuanceRecords{} }
func (m *RepIssuanceRecords) String() string { return proto.CompactTextString(m) }
func (*RepIssuanceRecords) ProtoMessage()    {}
func (*RepIssuanceRecords) Descriptor() ([]byte, []int) {
	return fileDescriptor_7110f4228953d675, []int{21}
}

func (m *RepIssuanceRecords) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepIssuanceRecords.Unmarshal(m, b)
}
func (m *RepIssuanceRecords) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepIssuanceRecords.Marshal(b, m, deterministic)
}
func (m *RepIssuanceRecords) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepIssuanceRecords.Merge(m, src)
}
func (m *RepIssuanceRecords) XXX_Size() int {
	return xxx_messageInfo_RepIssuanceRecords.Size(m)
}
func (m *RepIssuanceRecords) XXX_DiscardUnknown() {
	xxx_messageInfo_RepIssuanceRecords.DiscardUnknown(m)
}

var xxx_messageInfo_RepIssuanceRecords proto.InternalMessageInfo

func (m *RepIssuanceRecords) GetRecords() []*DebtRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

// 返回记录
type RepIssuanceDebtInfo struct {
	Record               *DebtRecord `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RepIssuanceDebtInfo) Reset()         { *m = RepIssuanceDebtInfo{} }
func (m *RepIssuanceDebtInfo) String() string { return proto.CompactTextString(m) }
func (*RepIssuanceDebtInfo) ProtoMessage()    {}
func (*RepIssuanceDebtInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7110f4228953d675, []int{22}
}

func (m *RepIssuanceDebtInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepIssuanceDebtInfo.Unmarshal(m, b)
}
func (m *RepIssuanceDebtInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepIssuanceDebtInfo.Marshal(b, m, deterministic)
}
func (m *RepIssuanceDebtInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepIssuanceDebtInfo.Merge(m, src)
}
func (m *RepIssuanceDebtInfo) XXX_Size() int {
	return xxx_messageInfo_RepIssuanceDebtInfo.Size(m)
}
func (m *RepIssuanceDebtInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RepIssuanceDebtInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RepIssuanceDebtInfo proto.InternalMessageInfo

func (m *RepIssuanceDebtInfo) GetRecord() *DebtRecord {
	if m != nil {
		return m.Record
	}
	return nil
}

// 返回最新抵押物价格
type RepIssuancePrice struct {
	Price                int64    `protobuf:"varint,1,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepIssuancePrice) Reset()         { *m = RepIssuancePrice{} }
func (m *RepIssuancePrice) String() string { return proto.CompactTextString(m) }
func (*RepIssuancePrice) ProtoMessage()    {}
func (*RepIssuancePrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_7110f4228953d675, []int{23}
}

func (m *RepIssuancePrice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepIssuancePrice.Unmarshal(m, b)
}
func (m *RepIssuancePrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepIssuancePrice.Marshal(b, m, deterministic)
}
func (m *RepIssuancePrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepIssuancePrice.Merge(m, src)
}
func (m *RepIssuancePrice) XXX_Size() int {
	return xxx_messageInfo_RepIssuancePrice.Size(m)
}
func (m *RepIssuancePrice) XXX_DiscardUnknown() {
	xxx_messageInfo_RepIssuancePrice.DiscardUnknown(m)
}

var xxx_messageInfo_RepIssuancePrice proto.InternalMessageInfo

func (m *RepIssuancePrice) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

// 返回用户发行总额
type RepIssuanceUserBalance struct {
	Balance              int64    `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepIssuanceUserBalance) Reset()         { *m = RepIssuanceUserBalance{} }
func (m *RepIssuanceUserBalance) String() string { return proto.CompactTextString(m) }
func (*RepIssuanceUserBalance) ProtoMessage()    {}
func (*RepIssuanceUserBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_7110f4228953d675, []int{24}
}

func (m *RepIssuanceUserBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepIssuanceUserBalance.Unmarshal(m, b)
}
func (m *RepIssuanceUserBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepIssuanceUserBalance.Marshal(b, m, deterministic)
}
func (m *RepIssuanceUserBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepIssuanceUserBalance.Merge(m, src)
}
func (m *RepIssuanceUserBalance) XXX_Size() int {
	return xxx_messageInfo_RepIssuanceUserBalance.Size(m)
}
func (m *RepIssuanceUserBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_RepIssuanceUserBalance.DiscardUnknown(m)
}

var xxx_messageInfo_RepIssuanceUserBalance proto.InternalMessageInfo

func (m *RepIssuanceUserBalance) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

// 返回所有发行用户
type RepIssuanceAddr struct {
	Addr                 []string `protobuf:"bytes,1,rep,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepIssuanceAddr) Reset()         { *m = RepIssuanceAddr{} }
func (m *RepIssuanceAddr) String() string { return proto.CompactTextString(m) }
func (*RepIssuanceAddr) ProtoMessage()    {}
func (*RepIssuanceAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_7110f4228953d675, []int{25}
}

func (m *RepIssuanceAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepIssuanceAddr.Unmarshal(m, b)
}
func (m *RepIssuanceAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepIssuanceAddr.Marshal(b, m, deterministic)
}
func (m *RepIssuanceAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepIssuanceAddr.Merge(m, src)
}
func (m *RepIssuanceAddr) XXX_Size() int {
	return xxx_messageInfo_RepIssuanceAddr.Size(m)
}
func (m *RepIssuanceAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_RepIssuanceAddr.DiscardUnknown(m)
}

var xxx_messageInfo_RepIssuanceAddr proto.InternalMessageInfo

func (m *RepIssuanceAddr) GetAddr() []string {
	if m != nil {
		return m.Addr
	}
	return nil
}

func init() {
	proto.RegisterType((*Issuance)(nil), "types.Issuance")
	proto.RegisterType((*DebtRecord)(nil), "types.DebtRecord")
	proto.RegisterType((*IssuanceAssetPriceRecord)(nil), "types.IssuanceAssetPriceRecord")
	proto.RegisterType((*IssuanceAction)(nil), "types.IssuanceAction")
	proto.RegisterType((*IssuanceManage)(nil), "types.IssuanceManage")
	proto.RegisterType((*IssuanceIssuer)(nil), "types.IssuanceIssuer")
	proto.RegisterType((*IssuanceCreate)(nil), "types.IssuanceCreate")
	proto.RegisterType((*IssuanceDebt)(nil), "types.IssuanceDebt")
	proto.RegisterType((*IssuanceRepay)(nil), "types.IssuanceRepay")
	proto.RegisterType((*IssuanceFeed)(nil), "types.IssuanceFeed")
	proto.RegisterType((*IssuanceClose)(nil), "types.IssuanceClose")
	proto.RegisterType((*ReceiptIssuance)(nil), "types.ReceiptIssuance")
	proto.RegisterType((*ReceiptIssuanceID)(nil), "types.ReceiptIssuanceID")
	proto.RegisterType((*IssuanceRecords)(nil), "types.IssuanceRecords")
	proto.RegisterType((*ReqIssuanceInfo)(nil), "types.ReqIssuanceInfo")
	proto.RegisterType((*RepIssuanceCurrentInfo)(nil), "types.RepIssuanceCurrentInfo")
	proto.RegisterType((*ReqIssuanceInfos)(nil), "types.ReqIssuanceInfos")
	proto.RegisterType((*RepIssuanceCurrentInfos)(nil), "types.RepIssuanceCurrentInfos")
	proto.RegisterType((*ReqIssuanceByStatus)(nil), "types.ReqIssuanceByStatus")
	proto.RegisterType((*RepIssuanceIDs)(nil), "types.RepIssuanceIDs")
	proto.RegisterType((*ReqIssuanceRecords)(nil), "types.ReqIssuanceRecords")
	proto.RegisterType((*RepIssuanceRecords)(nil), "types.RepIssuanceRecords")
	proto.RegisterType((*RepIssuanceDebtInfo)(nil), "types.RepIssuanceDebtInfo")
	proto.RegisterType((*RepIssuancePrice)(nil), "types.RepIssuancePrice")
	proto.RegisterType((*RepIssuanceUserBalance)(nil), "types.RepIssuanceUserBalance")
	proto.RegisterType((*RepIssuanceAddr)(nil), "types.RepIssuanceAddr")
}

func init() { proto.RegisterFile("issuance.proto", fileDescriptor_7110f4228953d675) }

var fileDescriptor_7110f4228953d675 = []byte{
	// 1101 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0x5f, 0x6f, 0xdc, 0x44,
	0x10, 0x8f, 0xed, 0xfb, 0x93, 0x9b, 0x4b, 0x2e, 0xe9, 0xb6, 0x04, 0x0b, 0x95, 0xea, 0xb4, 0x02,
	0xe9, 0x0a, 0x28, 0x2d, 0x17, 0x84, 0xc4, 0x5b, 0x93, 0x1c, 0x90, 0x13, 0xb4, 0x42, 0xa6, 0x54,
	0xbc, 0x3a, 0xf6, 0xb6, 0xb2, 0xe4, 0x9c, 0x5d, 0x7b, 0x2f, 0xea, 0x3d, 0xf3, 0x1d, 0x78, 0xe0,
	0xe3, 0xf0, 0x81, 0x78, 0xe0, 0x13, 0xa0, 0x99, 0x5d, 0x7b, 0xed, 0xf5, 0x45, 0x97, 0x27, 0x5e,
	0xa2, 0xdb, 0xd9, 0xdf, 0xce, 0x8e, 0xe7, 0xf7, 0x9b, 0x99, 0x0d, 0x4c, 0x92, 0xb2, 0x5c, 0x87,
	0xab, 0x48, 0x9c, 0xe6, 0x45, 0x26, 0x33, 0xd6, 0x97, 0x9b, 0x5c, 0x94, 0xfc, 0xef, 0x1e, 0xec,
	0x2f, 0xf5, 0x0e, 0x7b, 0x02, 0x50, 0xa1, 0x96, 0xb1, 0xef, 0x4c, 0x9d, 0xd9, 0x28, 0x68, 0x58,
	0x18, 0x87, 0x03, 0x99, 0xc9, 0x30, 0xbd, 0x08, 0x53, 0xb4, 0xf8, 0xee, 0xd4, 0x99, 0x79, 0x41,
	0xcb, 0xc6, 0xa6, 0x30, 0x8e, 0xc5, 0xb5, 0xbc, 0x14, 0x49, 0x9a, 0xac, 0xde, 0xf9, 0x1e, 0x41,
	0x9a, 0x26, 0xf6, 0x05, 0x1c, 0xa7, 0xc9, 0xfb, 0x75, 0x12, 0x87, 0x32, 0xc9, 0x56, 0x01, 0xfe,
	0xf5, 0x7b, 0x04, 0xeb, 0xd8, 0xd9, 0x0c, 0x8e, 0xa2, 0x2c, 0x4d, 0x43, 0x29, 0x8a, 0x30, 0x7d,
	0x13, 0xa6, 0x6b, 0xe1, 0xf7, 0x09, 0x6a, 0x9b, 0xd9, 0x63, 0x18, 0xe1, 0x25, 0x0a, 0x33, 0x20,
	0x8c, 0x31, 0xb0, 0x33, 0x15, 0x55, 0x20, 0xa2, 0xac, 0x88, 0x4b, 0x7f, 0x38, 0xf5, 0x66, 0xe3,
	0xf9, 0x83, 0x53, 0xca, 0xc1, 0xe9, 0xa2, 0xde, 0x09, 0x9a, 0x28, 0xf6, 0x1d, 0x4c, 0x92, 0xd5,
	0x6d, 0x98, 0x26, 0x71, 0x75, 0x6e, 0xff, 0xae, 0x73, 0x16, 0x90, 0x9d, 0xc0, 0xa0, 0x94, 0xa1,
	0x5c, 0x97, 0xfe, 0x68, 0xea, 0xcc, 0xfa, 0x81, 0x5e, 0xb1, 0x6f, 0xe1, 0x04, 0xa3, 0x2e, 0xe5,
	0xcf, 0xe6, 0x4b, 0x7f, 0x29, 0x92, 0x48, 0xf8, 0x40, 0x21, 0xdf, 0xb1, 0x8b, 0xfe, 0x72, 0x51,
	0x24, 0x59, 0xec, 0x8f, 0x09, 0xa7, 0x57, 0x94, 0x4b, 0x3a, 0xf1, 0xfd, 0x87, 0x3c, 0x29, 0xc4,
	0xeb, 0xe4, 0x46, 0xf8, 0x07, 0x3a, 0x97, 0x96, 0x1d, 0xd9, 0x8d, 0x0a, 0x11, 0x4a, 0x85, 0x3a,
	0x24, 0x54, 0xc3, 0xc2, 0x7c, 0x18, 0x5e, 0x6b, 0x62, 0x27, 0xb4, 0x59, 0x2d, 0x2b, 0x5d, 0x88,
	0xe2, 0x3c, 0x8e, 0x0b, 0xff, 0xc8, 0xe8, 0x42, 0x59, 0xf8, 0x9f, 0x1e, 0x80, 0x49, 0x06, 0x4a,
	0x20, 0x8c, 0xa2, 0x6c, 0xbd, 0x92, 0x84, 0x57, 0x3a, 0x6a, 0x9a, 0x90, 0xac, 0x52, 0x86, 0x85,
	0xa4, 0x48, 0x94, 0x8a, 0x8c, 0x61, 0x1b, 0xe9, 0xde, 0x76, 0xd2, 0x5b, 0x48, 0x95, 0xc7, 0x9e,
	0x8d, 0x54, 0x09, 0x6c, 0xc9, 0xa3, 0x6f, 0xcb, 0xa3, 0x2d, 0x49, 0xe5, 0x68, 0xd0, 0x91, 0x64,
	0x4d, 0x85, 0xa6, 0x76, 0xd8, 0xa2, 0xf6, 0x33, 0x38, 0xac, 0xb0, 0x2a, 0xc3, 0xfb, 0xe4, 0xa0,
	0x6d, 0xc4, 0x54, 0x0a, 0x43, 0xd5, 0x48, 0x91, 0x60, 0x2c, 0x18, 0x67, 0x5e, 0x88, 0x5f, 0xd5,
	0x05, 0x40, 0x17, 0x18, 0x03, 0xde, 0x8d, 0x41, 0x2f, 0x95, 0x0c, 0x46, 0x81, 0x5e, 0xa1, 0x1d,
	0xe9, 0x58, 0xc6, 0x44, 0xfe, 0x28, 0xd0, 0x2b, 0xfe, 0x06, 0xfc, 0xaa, 0xb8, 0xcf, 0xcb, 0x52,
	0x48, 0xfa, 0x02, 0xcd, 0xd2, 0x13, 0x80, 0x82, 0x7e, 0x51, 0x24, 0x8e, 0x8a, 0xc4, 0x58, 0xd8,
	0x27, 0xb0, 0x7f, 0x2d, 0x37, 0x2a, 0x17, 0x8a, 0xa2, 0x7a, 0xcd, 0xff, 0x71, 0x61, 0x52, 0x3b,
	0x8e, 0x30, 0x37, 0xec, 0x19, 0x0c, 0x94, 0x96, 0xc8, 0xd5, 0x78, 0xfe, 0x91, 0x2e, 0x92, 0x0a,
	0x76, 0x49, 0x9b, 0x57, 0x7b, 0x81, 0x86, 0xb1, 0xa7, 0xd0, 0xc3, 0xe8, 0xc9, 0xf7, 0x78, 0xfe,
	0xd0, 0x82, 0xa3, 0x9c, 0xae, 0xf6, 0x02, 0x82, 0xb0, 0xaf, 0xa0, 0x5f, 0x88, 0x3c, 0xdc, 0x90,
	0x0c, 0xc6, 0xf3, 0x47, 0x16, 0x36, 0xc0, 0xbd, 0xab, 0xbd, 0x40, 0x81, 0xd0, 0xf1, 0x5b, 0x21,
	0x62, 0x52, 0x42, 0xd7, 0xf1, 0x0f, 0x42, 0xc4, 0xe8, 0x18, 0x21, 0xe8, 0x38, 0x4a, 0xb3, 0x52,
	0x29, 0xa2, 0xeb, 0xf8, 0x12, 0xf7, 0xd0, 0x31, 0x81, 0xf0, 0x13, 0x6f, 0xc2, 0x55, 0xf8, 0x4e,
	0x69, 0xa3, 0xfb, 0x89, 0x2f, 0x69, 0x13, 0x3f, 0x51, 0xc1, 0xf0, 0x80, 0xaa, 0x12, 0x92, 0x4a,
	0xf7, 0xc0, 0x92, 0x36, 0xf1, 0x80, 0x82, 0xb1, 0x09, 0xb8, 0x72, 0xa3, 0x69, 0x77, 0xe5, 0xe6,
	0x62, 0x08, 0xfd, 0x5b, 0x14, 0x28, 0x7f, 0x6e, 0xf2, 0xad, 0x6e, 0x41, 0xfa, 0xca, 0x75, 0xae,
	0x0a, 0xb0, 0xf4, 0x9d, 0xa9, 0x87, 0x35, 0x69, 0x2c, 0xfc, 0x85, 0x39, 0xa1, 0xae, 0xb1, 0xaa,
	0xd8, 0xb1, 0xab, 0x18, 0x2f, 0xcf, 0x72, 0xa2, 0x63, 0x14, 0xb8, 0x59, 0xce, 0xff, 0x72, 0x8c,
	0x0b, 0xc5, 0x5e, 0x67, 0x00, 0x38, 0xbb, 0x07, 0x80, 0x7b, 0xbf, 0x01, 0xe0, 0xdd, 0x31, 0x00,
	0x4c, 0xe3, 0xeb, 0x35, 0x1b, 0x1f, 0x5f, 0xc0, 0x41, 0x53, 0x2a, 0x3b, 0x47, 0xd7, 0x23, 0x9d,
	0x49, 0x1d, 0x8f, 0x4e, 0xeb, 0x8f, 0x70, 0xd8, 0x12, 0xd1, 0x4e, 0x37, 0xa6, 0x00, 0xdd, 0x66,
	0x01, 0xf2, 0xdf, 0x4d, 0x38, 0x28, 0x30, 0x2c, 0x1e, 0xec, 0x40, 0xaf, 0x37, 0xb9, 0x4a, 0x52,
	0x3f, 0xa8, 0xd7, 0x18, 0x4a, 0xae, 0xab, 0xca, 0xc3, 0x50, 0xf2, 0xaa, 0xad, 0xdc, 0x66, 0xe9,
	0xfa, 0x06, 0x7b, 0x1d, 0x9a, 0xf5, 0x8a, 0x3f, 0x33, 0x21, 0x92, 0x1c, 0x77, 0x85, 0xc8, 0xff,
	0x70, 0xe0, 0x28, 0x10, 0x91, 0x48, 0x72, 0x79, 0xef, 0xc1, 0x6e, 0x75, 0x6c, 0xb7, 0xdb, 0xb1,
	0xcd, 0x87, 0x7b, 0x76, 0xe7, 0xd1, 0xdd, 0xb0, 0xd7, 0xec, 0x86, 0xfc, 0x27, 0x78, 0x60, 0x05,
	0xb1, 0x5c, 0xdc, 0x27, 0xbb, 0xda, 0x99, 0xdb, 0x72, 0x76, 0x09, 0x47, 0x86, 0x26, 0x35, 0x60,
	0x9f, 0xc3, 0xb0, 0xd0, 0x43, 0xd9, 0xa1, 0xa1, 0x7c, 0xa2, 0x6b, 0xcb, 0xba, 0x35, 0xa8, 0x60,
	0xfc, 0x6b, 0x4c, 0xcb, 0xfb, 0x3a, 0x9a, 0xd5, 0xdb, 0x6c, 0x67, 0x2a, 0xff, 0x75, 0xe1, 0x24,
	0x10, 0x79, 0x9d, 0xff, 0x75, 0x51, 0x88, 0x95, 0xa4, 0xa3, 0x26, 0x54, 0xa7, 0x35, 0x05, 0xfe,
	0xff, 0x27, 0x52, 0x63, 0x6c, 0xf7, 0xdb, 0x63, 0x7b, 0xcb, 0x1c, 0x1d, 0xdc, 0xe3, 0xf1, 0x34,
	0xb4, 0xa7, 0xa3, 0xa9, 0xc1, 0xfd, 0xd6, 0xe3, 0xc3, 0x4c, 0x9d, 0x51, 0x73, 0xea, 0x58, 0x0f,
	0x0d, 0xe8, 0x3c, 0x34, 0x1e, 0xc3, 0x48, 0x91, 0xf2, 0x6a, 0x7d, 0xa3, 0xdf, 0x33, 0xc6, 0xc0,
	0xbf, 0x81, 0x63, 0x8b, 0xa7, 0x12, 0x33, 0x66, 0x68, 0xa9, 0xba, 0x5d, 0xd3, 0xc4, 0x5f, 0xc1,
	0xc7, 0xdb, 0x99, 0x2a, 0xd9, 0x19, 0xf4, 0x13, 0xfc, 0xa1, 0x85, 0xf2, 0x69, 0x2d, 0x94, 0x6d,
	0xf0, 0x40, 0x61, 0xf9, 0x4b, 0x78, 0xd8, 0x88, 0xe2, 0x62, 0x63, 0x06, 0xf0, 0x56, 0xda, 0xdb,
	0x4a, 0x72, 0x3b, 0x4a, 0xe2, 0x30, 0x69, 0xdc, 0xb7, 0x5c, 0x94, 0xec, 0x18, 0xbc, 0xe5, 0xa2,
	0xfa, 0x14, 0xfc, 0xc9, 0x3f, 0x00, 0x6b, 0x5c, 0x59, 0x09, 0x7d, 0x57, 0xcd, 0x30, 0xe8, 0x85,
	0xa6, 0x66, 0xe9, 0x77, 0x23, 0x4a, 0xaf, 0x15, 0xa5, 0x29, 0xe2, 0x5e, 0xab, 0x7b, 0x9d, 0xe3,
	0xcd, 0xb9, 0x7d, 0xf3, 0x97, 0x76, 0x89, 0x6d, 0x79, 0xf7, 0xd6, 0xd5, 0xf5, 0x02, 0xf3, 0x95,
	0x37, 0x5b, 0x32, 0x95, 0xc9, 0x53, 0x18, 0x28, 0x84, 0x7e, 0x15, 0x6c, 0x71, 0xa1, 0x01, 0x7c,
	0x86, 0xbc, 0xd7, 0x1e, 0xd4, 0x5b, 0xab, 0x6e, 0x95, 0x6a, 0xd0, 0xa8, 0x05, 0x9f, 0xb7, 0xaa,
	0xf2, 0xb7, 0x52, 0x14, 0x55, 0x65, 0x35, 0x6a, 0xc1, 0x69, 0xd5, 0x02, 0xff, 0x1c, 0xab, 0xbf,
	0x3e, 0x43, 0x2d, 0xad, 0xca, 0x9c, 0xa2, 0x80, 0x7e, 0x5f, 0x0f, 0xe8, 0x9f, 0xa3, 0xb3, 0xff,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xb0, 0xf1, 0x94, 0x84, 0x2e, 0x0d, 0x00, 0x00,
}
